### ISSUE TITLE
Delimitación de unidades administrativas

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#10]
Delimitar de forma pareja los límites entre las comunas, provincias, regiones, distrito censal, cuencas, subcuencas y subsubcuencas. En la Figura 1 sólo se presenta la división entre comunas, sin embargo, esto se repite para todas las unidades administrativas y para todas las combinaciones de variables cuando la opción de macrozonas “Todas” está activada. Cuando se selecciona una macrozona (norte grande, norte chico, etc) se arregla la delimitación de las comunas (figura 2). 

![imagen](https://user-images.githubusercontent.com/128641014/228894844-7d517ceb-4220-4bb9-a61d-b9291c0412a1.png)
Figura 1. Delimitación errónea de las unidades administrativas

![imagen](https://user-images.githubusercontent.com/128641014/228894900-99c3054e-f2c2-4b8b-8369-a4ed1547b63f.png)
Figura 2. División correcta de las unidades administrativas

**Comment by jbkunst** [comment]
@frzambra  realizar pruebas con flac geo base

antes de colocar la version NO simplificada (lenta)

**Comment by frzambra** [comment]
No muy buenas noticias, `leafem::addFgb` está en desarrollo, [acá](https://github.com/r-spatial/leafem/issues/24#issuecomment-905420251) hay un issue que tiene que ver con esto, pero no hay respuesta.

Tim no ha continuado con la mantención, pasa lo mismo con `leafem::addCOG`, yo le dejé un [issue](https://github.com/r-spatial/leafem/issues/65) pero no hay respuesta. Esperemos que aparezca con versiones nuevas pronto.

Acá comparto las alternativas que pensé podrian servir:

guardar como flatGeoBuf (.fgb)
 
```r
library(sf)
library(leafem)
library(mapview)

dc <- read_sf('data/raw/distrito_censal.gpkg')

mapview(dc) |> class() #objeto mapview

mapview(dc)@map |> class() #objeto leaflet

#con addPolygons 

leaflet(dc) |> 
leaflet::addPolygons(
    data = data_geo,
  )

dc$valor <- runif(nrow(dc),-5,5)
pal <- colorBin('RdYlBu',dc$valor, 10, pretty = TRUE, reverse = TRUE)
dc$fillColor <- pal(dc$valor)

write_sf(dc,'data/distrito_censal.fgb')

#con addFgb

leaflet(dc) |> 
   leafem::addFgb(
        file ='data/distrito_censal.fgb',
        fill =TRUE,
        stroke = NULL)
```
Ahora, implementando esto en shiny es el problema

```r
library(shiny)
library(rnaturalearth)
library(leaflet.extras)
library(sf)
library(leafem)

chl <- ne_countries(country = 'chile',returnclass = 'sf') |> st_transform(4326)

ui <- fluidPage(
  leafletOutput("map1")
)

map <- leaflet() |>  
  addTiles() |> 
  addPolygons(data = chl) |> 
  #addSearchGoogle()
  addSearchOSM(options = searchOptions(
    textErr = "Ubicación no encontrada", textCancel = "Cancelar",
    textPlaceholder = "Buscar...",
    position = 'topleft')) |>
  addEasyButton(easyButton(
    icon = "fa-crosshairs",
    onClick=JS("function(btn, map){ map.locate({setView: true}); }")))
```

## opción 1: intentando utilizar mapview, esto genera error

```r
server <- function(input, output, session) {
  output$map1 <- renderLeaflet(map)
  
  observeEvent(input$map1_click, {
    leafletProxy("map1", session)  |> 
      clearShapes() %>% 
      mapview(dc)@map 
    })
}

app <- shinyApp(ui, server)
app
```

## opción 2: llamando el archivo .fgb funciona, pero la función `leafem::addFgb` aún no está completamente desarrollada, por lo que las highlightOptions no funcionan (ver [issue](https://github.com/r-spatial/leafem/issues/24#issuecomment-905420251))

```r
server <- function(input, output, session) {
  output$map1 <- renderLeaflet(map)
  
  observeEvent(input$map1_click, {
    leafletProxy("map1", session)  |> 
      clearShapes() |>  
      addFgb(
        file ='data/distrito_censal.fgb',
        fill =TRUE,
        stroke = NULL,
        highlightOptions = highlightOptions(color = "white", weight = 4,fillColor = parametros$color,bringToFront = TRUE),
        labelOptions = labelOptions(
          # offset = c(-20, -20),
          style = list(
            "font-family" = parametros$font_family,
            "box-shadow" = "2px 2px rgba(0,0,0,0.15)",
            "font-size" = "15px",
            "padding" = "15px",
            "border-color" = "rgba(0,0,0,0.15)"
          )
        )) 
  })
}

app <- shinyApp(ui, server)
app
```

## Conclusión

Creo que la mejor opción sería no dejar que se muestren todas las unidades y solo por macrozona, quizas ese selector puede estar separado sobre el mapa donde se muestren las 5 macrozonas y se pueda seleccionar sólo una. De esa manera quedan menos selectores en la parte de la izquierda, creo que más simple.

**Comment by fabian199827** [comment]
Algo así es lo del comentario de de "Conclusión"? (Figura 1)
![imagen](https://user-images.githubusercontent.com/128641014/234645092-80e838d0-a618-4ccf-b4bf-ae4752accf5f.png)
Figura 1

Algo así se me ocurre a mi (Figura 2)
![modificación panel](https://user-images.githubusercontent.com/128641014/234649375-2ea74313-d7ee-4af9-958a-bffab08e08ad.png)

**Comment by jbkunst** [comment]
No creo, Francisco solamente dijo que no se diera la posibildiad de seleccionar Todas las macrozonas, lo que simplemente se elimina como opción.

Ahora, lo que propones en tus gráficos no es lo estándar, y no se como funcionaría cuando la pantalla sea más angosta (como de un celular).

Saludos,

**Comment by fabian199827** [comment]
Okey, entiendo, lo había entendido mal, y tienes razón ese formato de los gráficos que mandé, sería poco eficiente la dinámica de la página. Entonces podría quedar de esta forma:

![imagen](https://user-images.githubusercontent.com/128641014/235170115-ca13793f-82f2-40e4-a3b1-e53e7f9bff44.png)

Mi pregunta es si se podrán seleccionar varias macrozonas (ahí se reemplazaría la opción de marcar todas)? o se seleccionará de a una?

**Comment by jbkunst** [comment]
Ok: 

![image](https://user-images.githubusercontent.com/56481/235181428-472d920f-e0a2-4108-9b8c-65f62272b214.png)
