### ISSUE TITLE
Opción minimizar

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#11]
Agregar opción para minimizar/ocultar el menú para que se pueda visualizar de mejor forma el mapa
![imagen](https://user-images.githubusercontent.com/128641014/228895565-5a45ab71-be1f-4fdc-875f-ea7863d48304.png)

**Comment by jbkunst** [comment]
Agregar icono de flecha/triangulo, hacia arriba/abajo
