### ISSUE TITLE
Desconexión de servidor

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#12]
@jbkunst @frzambra dentro de este mismo issue subiré  las caidas de página que ha tenido la sección de unidades, para que las revisemos en conjunto y veamos si es tema del plan del servidor o de algún error de las bases de datos. Estas fallas las iré actualizando a medida que vayan ocurriendo:

1) se selecciona: zona austral +  regiones +  precipitación y se cae. Se repite esta falla con la zona austral.  Esto sucede con todas la combinaciones de  unidades administrativas y con todas las combinaciones de variables. Existe un **ERROR IMPORTANTE CON LA ZONA AUSTRAL**

2) Estado incial del panel macro zona sur + regiones + preciítación . Se selecciona: 
macrozona sur + comunas + precipitacion y se cae
macrozona sur + comunas + T°min y se cae
macrozona sur + comunas + SPI 6 meses y se cae (después de la primera caída, vuelve a hacer esta combinación y no se cae)
macrozona sur + provincias + SPI 24 meses y se cae (después de la primera caída, vuelve a hacer esta combinación y no se cae)
macrozona sur + distrito censal + demanda evapotranspirativa de la atmosfera se cae
macrozona sur + distrito censal + precipitación se cae

3) Mucho tiempo de espera cuando se cambia de macrozona, unidad administrativa o variable. Esto sucede aveces, sin embargo lo documento igual.

4) Se mueve el selector de fechas y se cae la página

5) se slecciona:
Macrozona todas + provincias +  SPEI 3 recorro las distintas regiones para ver un error en el minigráfico y se cae la pagina. Se repite en reiteradas ocasiones este error, y luego se demora aproximadamente 5 minutos en volver a fincionar la plataforma.

6) Se cambian todas las variables de: Macrozona, Unidad administrativa y variable. La página se cae

7) Cambio de provincia a comuna teniendo esta combinación al principio: Todas +  Provincia +  SPI24

8) Después de muchos intentos de poner la combinación: Todas + comunas + SPEI 1. La página se cae y no me permite ver esta combinación de variables

9) Estado inicial panel: Zona sur + comunas + precipitacion. Se cambia a: Zona sur + distrito censal + precipitación. se cae la página

10) Al momento de pinchar en generar reporte se cae el servidor. La combinación de selectores es: Zona central, regiones, precipitación. Se selecciona para descargar el reporte de la RM y la página se cae

**Comment by jbkunst** [comment]
Revisar la posibilidad de testear plan básico
![image](https://user-images.githubusercontent.com/56481/229210454-52f3c489-13b9-4b6a-ad12-648be8fa3031.png)

**Comment by fabian199827** [comment]
El mismo error aparece cuando se selecciona la macrozona Austral
![imagen](https://user-images.githubusercontent.com/128641014/231540425-ef449a1b-a71e-4a15-ae2d-d68dffc12fc2.png)

**Comment by frzambra** [comment]
@jbkunst, probé otra simplificación (ver [codigo](https://github.com/ODES-Chile/odes-unidades-shiny-app/blob/main/R/03_simplify_geoms_rmapshaper.R)) para las geometrias, ahora todas deben cerrar y no tener espacio entre lineas. El tamaño de los archivos es < 1.7 MB, por lo que con estas geometrias ahora la carga debería ser muy rapida. Los archivos quedaron [acá](https://github.com/ODES-Chile/odes-unidades-shiny-app/tree/main/data/vectorial/min), tienen como nombre `{nombre_unidad}_sim.gpkg`

**Comment by jbkunst** [comment]
Tomes los pgpk y les corregí los nombres y todo ok! se nota la mejora totalmente. Tanto en local como en shinyapps. Ahora probaré con mi cuenta (starter) para probar en un escenario donde no hay muchos recursos.

https://frzambra.shinyapps.io/odes-unidades-shiny-app/
https://jbkunst.shinyapps.io/odes-unidades-shiny-app/
