### ISSUE TITLE
Falta identificar indicador SPI y SPEI

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#14]
No hay indicador SPI en gran parte del territorio del norte de Chile (Figura 1). No hay indicador SPEI en parte del territorio sur (figura 2).
![imagen](https://user-images.githubusercontent.com/128641014/228898428-b83afede-4ea3-461a-8255-916406792b28.png)
Figura 1. Sin indicador SPI 

![imagen](https://user-images.githubusercontent.com/128641014/228898490-c0992323-99c2-4bba-a75f-f335174f4b37.png)
Figura 2. Sin indicador SPEI.

**Comment by fabian199827** [comment]
@frzambra creo que esto ya se solucionó? ahora veo esto en la pagina:
 
![imagen](https://user-images.githubusercontent.com/128641014/234344338-aaa2a4e5-0803-4c1b-b0d0-9f0850a7bad0.png)

![imagen](https://user-images.githubusercontent.com/128641014/234344629-47973ebd-71f9-4ffb-86f9-4b6d81fa84d0.png)

Sólo que ahora hay algunos lugares que no está disponible el indicador. Cierro este issue?

También para que hay zonas del mapa que no tienen nada de información se ve blanco:
![imagen](https://user-images.githubusercontent.com/128641014/234920767-bc0bfcab-76c5-4538-9899-cbc0cc2584a3.png)

**Comment by frzambra** [comment]
@fabian199827 esto hay que seguir revisando, no se si con los cambios que hizo @jbkunst de acuerdo a lo revisado por @joaquinRiquelme, siguen faltando valores de los indicadores de sequía (SPIs y SPEIs) o están todos completos. Si encuentras uno o varios casos, favor documentar aquí algunos ejemplos.

**Comment by fabian199827** [comment]
SPEI: Revisar esto @frzambra 

**Regiones:**
Con la combinación de selectores presentados en la figura 1 se ve que en el norte grande el indicador SPEI aparece como no disponible.
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/d51161c2-860b-4210-aad8-a5a8a478c392)
Figura 1

**Distrito censal:**
Existe categoría no disponible cuando se selecciona distito censal y todas la macrozonas, que a simple vista no se ve cuál es (Figura 2) pero cuando se comienza a buscar, se ve que en las ciudades existen distritos censales con NA (Figura 3).
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/534bd5f1-7368-4256-9e1d-f4cd54807027)
Figura 2

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/bd5a0758-48ec-47b8-95b2-a5f8744d30c9)
Figura 3

**Provincia:**
Se ve bien a simple vista (Figura 4) pero hay llugares con NA como la isla de pascua (Figura 5)
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/0d04ce6b-30c6-40da-8edb-928dfebba596)
Figura 4

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/4e93e097-328f-4069-a07e-97a9cd1a6ab2)
Figura 5

**Comunas:**
Comunas con NA islas juan fernandes e isla de pascua. Error con las islas.
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/78175a7e-4cb9-4a14-b7b1-dcb81966c18f)

**Subcuencas:**
Isla diego Ramirez con NA entre otras
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/fb3818a5-5a66-4897-bc88-2e3a39a21959)

**Subsubcuencas:**
Isla robinson crusoe entre otras con NA
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/ba4e49d4-6da9-4202-8cc0-d4f24dd3ac3e)

Hay zonas sin valores
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/233a2575-bcf6-4f50-91c4-510e2e8635f3)


Todas estas situaciones documentadas se repitan para SPI.

**Comment by fabian199827** [comment]
Es raro porque aparece sin datos en los lugares en gris pero si se registran datos en el mini gráfico

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/d56783ca-ec96-42a7-b370-8b8d3ee81492)

Lo mismo en este caso
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/3660f4b1-4b48-4c16-bc86-4c3247763090)

**Comment by fabian199827** [comment]
@frzambra chequear datos spi y spei

**Comment by frzambra** [comment]
@fabian199827 revisar con los nuevos datos
