### ISSUE TITLE
Codificación y ortografía

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#17]
Cuando se selecciona la unidad administrativa de distrito censal, y subsubcuencas existe un error de codificación de texto, aparece un “?” y otro símbolo extraño como se muestra en la figura 1, 2 y 3 respectivamente (al parecer estas situaciones se dan cuando se escriben letras “N” o tildes. En cuanto a la ortografía: Faltan tildes cuando se seleccionan las unidades administrativas de cuenca, subcuenca, subsubcuenca y distritos censales.
![imagen](https://user-images.githubusercontent.com/128641014/228932379-d3080a79-99aa-490c-972d-9a2c56ddaa8f.png)
Figura 1. Error de codificación
![imagen](https://user-images.githubusercontent.com/128641014/228932406-49d7ab2d-887a-4c9b-91e5-e8ec2fa95bbc.png)
Figura 2. Error de codificación
![imagen](https://user-images.githubusercontent.com/128641014/228932465-b526d9d7-3fec-4beb-9691-fd681dfbec07.png)
Figura 3. Error de codificación
![imagen](https://user-images.githubusercontent.com/128641014/228932537-d08e4ee7-b8e4-4dc9-b12c-a7923c170e0a.png)
Figura 4. Error de escritura y ortografía

**Comment by jbkunst** [comment]
@frzambra realizará un check a los datos originales.
@jbkunst realizará un check a los datos para ver si existe la posibilidad de corregirlos.

**Comment by fabian199827** [comment]
Corregí los tildes y faltas de ortografía de la capa de cuencas. Adjunto archivo .txt para revisar, no sé como se podrá corregir esto a ivel de programación, asi que dejo un archivo de texto plano. No pude conseguir las capas de  subcuenca, subsubcuenca y distritos censales para corregirlas de lamisma forma.

[cuencas.txt](https://github.com/ODES-Chile/odes-unidades-shiny-app/files/11159391/cuencas.txt)

**Comment by jbkunst** [comment]
@fabian199827  DGA?

**Comment by fabian199827** [comment]
@jbkunst @frzambra a continuación subo la corrección de codificación y ortografía de las unidades con problemas: cuenca, subcuenca, subsubcuencas y distritos censales.

[cuencas.xlsx](https://github.com/ODES-Chile/odes-unidades-shiny-app/files/11323680/cuencas.xlsx)
[subcuencas.xlsx](https://github.com/ODES-Chile/odes-unidades-shiny-app/files/11323683/subcuencas.xlsx)
[subsubcuencas.xlsx](https://github.com/ODES-Chile/odes-unidades-shiny-app/files/11323687/subsubcuencas.xlsx)
[distritos_censales.xlsx](https://github.com/ODES-Chile/odes-unidades-shiny-app/files/11323689/distritos_censales.xlsx)

**Comment by jbkunst** [comment]
don @fabian199827  por favor testear cuando pueda

**Comment by fabian199827** [comment]
@jbkunst Trato de verificar esto, y puedo llegar sólo hasta subcuenca (esto esta bien) pero subsubcuenca  y distrito censales se cae la página con el sgte mensaje 😢 : 
![image](https://user-images.githubusercontent.com/128641014/236512927-851214e9-a318-4d0a-acd7-28161525efed.png)

**Comment by jbkunst** [comment]
Asociado a #12
