### ISSUE TITLE
Agregar metadata a gráfico de reporte de datos

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#19]
Agregar una metadata del contenido del gráfico para hacerlo más explicativo. Ej: Hacer click en el ícono “metadata” y que se despliegue un panel con la información que contiene el gráfico.

![imagen](https://user-images.githubusercontent.com/128641014/228933292-7c14f4a6-6847-4d87-bc72-877bba2b98da.png)

**Comment by jbkunst** [comment]
Quedamos a la espera de la descripción/texto.

**Comment by fabian199827** [comment]
Textos tentativos sujetos a cambios, esperando aprobación @frzambra :

**Texto metadata gráfico precipitación:**
Precipitación acumulada mensual, desde 2011 a 2019. Este gráfico permite comparar la cantidad precipitación entre distintos años.

**Texto metadata gráfico demanda evaporativa de la atmósfera**
Evapotranspiración promedio mensual desde 2011 a 2019. Este gráfico permite comparar la evapotranspiración en distintos años.

**Texto descriptivo gráfico temperatura**
Temperatura promedio mensual desde 2011 a 2019. Este gráfico permite comparar la variación de temperaturas en distintos años.

**Texto descriptivo SPEI 1**
Índice de sequía SPEI. Este índice indica la anomalía de la precipitación menos la evapotranspiración en 1 mes entre los años 2011 y 2019.

**Texto descriptivo SPEI 3**
Índice de sequía SPEI. Este índice indica la anomalía de la precipitación menos la evapotranspiración en 3 mes entre los años 2011 y 2019.

**Texto descriptivo SPEI 6**
Índice de sequía SPEI. Este índice indica la anomalía de la precipitación menos la evapotranspiración en 6 mes entre los años 2011 y 2019.

**Texto descriptivo SPEI 9**
Índice de sequía SPEI. Este índice indica la anomalía de la precipitación menos la evapotranspiración en 9 mes entre los años 2011 y 2019.

**Texto descriptivo SPEI 12**
Índice de sequía SPEI. Este índice indica la anomalía de la precipitación menos la evapotranspiración en 12 mes entre los años 2011 y 2019.

**Texto descriptivo SPEI 24**
Índice de sequía SPEI. Este índice indica la anomalía de la precipitación menos la evapotranspiración en 24 mes entre los años 2011 y 2019.

**Texto descriptivo SPI 1**
Indice de sequía SPI. Este índice indica la anomalía de la precipitación acumulada en 1 mes entre los años 2011 y 2019.

**Texto descriptivo SPI 3**
Indice de sequía SPI. Este índice indica la anomalía de la precipitación acumulada en 3 mes entre los años 2011 y 2019.

**Texto descriptivo SPI 6**
Indice de sequía SPI. Este índice indica la anomalía de la precipitación acumulada en 6 mes entre los años 2011 y 2019.

**Texto descriptivo SPI 9**
Indice de sequía SPI. Este índice indica la anomalía de la precipitación acumulada en 9 mes entre los años 2011 y 2019.

**Texto descriptivo SPI 12**
Indice de sequía SPI. Este índice indica la anomalía de la precipitación acumulada en 12 mes entre los años 2011 y 2019.

**Texto descriptivo SPI 24**
Indice de sequía SPI. Este índice indica la anomalía de la precipitación acumulada en 24 mes entre los años 2011 y 2019.
