### ISSUE TITLE
Se agregó tabla "data_clima_sequia" a BBDD

### ISSUE THREAD

**Issue by frzambra** [ODES-Chile/odes-unidades-shiny-app#21]
Hay que hacer los cambios para que la aplicación use la tabla de la BBDD

```r
Rows: 2,554,464
Columns: 18
$ code      <chr> "0110101", "0110101", "0110101", "0110101", "0110101", "0110101", "0110101", "0110…
$ unit      <chr> "distrito_censal", "distrito_censal", "distrito_censal", "distrito_censal", "distr…
$ date      <date> 1979-02-01, 1979-03-01, 1979-04-01, 1979-05-01, 1979-06-01, 1979-07-01, 1979-08-0…
$ pet       <dbl> 144.400, 141.695, 106.910, 87.585, 74.610, 76.645, 91.080, 109.155, 130.740, 142.7…
$ pre       <dbl> 3.70, 4.60, 22.55, 37.65, 38.40, 43.80, 41.40, 38.05, 20.85, 18.00, 19.25, 10.40, …
$ tas       <dbl> 29.4600, 29.4300, 29.1600, 29.0500, 28.9100, 28.8200, 28.8200, 28.9050, 28.9500, 2…
$ tasmax    <dbl> 29.74, 29.68, 29.47, 29.35, 29.21, 29.14, 29.11, 29.16, 29.23, 29.40, 29.60, 29.74…
$ tasmin    <dbl> 29.190, 29.230, 28.870, 28.780, 28.630, 28.500, 28.500, 28.610, 28.680, NA, NA, 29…
$ `SPEI-1`  <dbl> -1.46116817, -1.41830379, 1.61846578, 1.16027671, 0.66472593, 0.87626129, 0.941439…
$ `SPEI-12` <dbl> NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, 0.6790027, 0.6802467, 0.735…
$ `SPEI-24` <dbl> NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, Na…
$ `SPEI-3`  <dbl> NaN, NaN, -0.38663839, 1.12752241, 0.95519894, 0.76263392, 0.69586071, 0.97836864,…
$ `SPEI-6`  <dbl> NaN, NaN, NaN, NaN, NaN, 0.7025135, 0.7972795, 0.9579071, 0.7863350, 0.6770940, 0.…
$ `SPI-1`   <dbl> -1.30267102, -1.68193728, 1.71027690, 0.86320850, 0.48086728, 0.59685469, 0.783020…
$ `SPI-12`  <dbl> NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, 0.5382415, 0.5248244, 0.5546014,…
$ `SPI-24`  <dbl> NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, Na…
$ `SPI-3`   <dbl> NaN, -1.663633823, -0.470923200, 0.859218299, 0.736095726, 0.617113501, 0.60678106…
$ `SPI-6`   <dbl> NaN, NaN, NaN, NaN, 0.37467906, 0.51499903, 0.69652975, 0.87404975, 0.73408529, 0.…
```

**Comment by jbkunst** [comment]
Hola @frzambra ,

Estoy haciendo el cambio/integración de estos datos. Puedo pedirte  dos cosas respecto a la tabla por favor 🙏?

(1) Si puedes corregir la categoría provincias, dice "provinicas":

![image](https://user-images.githubusercontent.com/56481/231348107-64a53781-5176-4bef-ba94-f55b5b01bbda.png)

(2) Si puedes subir los nombres en minúsculas y separados por `_`.

![image](https://user-images.githubusercontent.com/56481/231348033-5cc9ab37-9834-4ff7-9cd9-72fc8eb43197.png)

**Comment by frzambra** [comment]
@frzambra agregar columna con variables categoricas para los indicadores de sequía

**Comment by fabian199827** [comment]
Los colores correspondientes a representar la mayor o menor cantidad de precipitación no corresponden a lo que es realmente, ya que el color que indica la mayor cantidad de precipitación es en norte de chile, y en el sur de chile se identifica como que no lloviera o lloviera muy poco.

![imagen](https://user-images.githubusercontent.com/128641014/231830521-a4169374-16f9-4dff-8d83-79d50d115404.png)

Esto lo identifico en este issue debido a que con la modificación de la base de datos, se arreglará la escala y de forma extra hay que chekear lo antes mencionado.

**Comment by frzambra** [comment]
> @frzambra agregar columna con variables categoricas para los indicadores de sequía

@jbkunst acá está arreglado, además incluí versiones categoricas para los indices de sequía spi y spei


```r
data <- dbReadTable(con, "data_clima_sequia") 
 data \|> 
glimpse() 

Rows: 2,554,464 
Columns: 28 
$ code        <chr> "0110101", "0110101", "0110101", "0110101", "0110101… 
$ unit        <chr> "distrito_censal", "distrito_censal", "distrito_cens… 
$ date        <date> 1979-02-01, 1979-03-01, 1979-04-01, 1979-05-01, 197… 
$ pet         <dbl> 144.400, 141.695, 106.910, 87.585, 74.610, 76.645, 9… 
$ pre         <dbl> 3.70, 4.60, 22.55, 37.65, 38.40, 43.80, 41.40, 38.05… 
$ tas         <dbl> 29.4600, 29.4300, 29.1600, 29.0500, 28.9100, 28.8200… 
$ tasmax      <dbl> 29.74, 29.68, 29.47, 29.35, 29.21, 29.14, 29.11, 29.… 
$ tasmin      <dbl> 29.19, 29.23, 28.87, 28.78, 28.63, 28.50, 28.50, 28.… 
$ spei_1      <dbl> -1.46116817, -1.41830379, 1.61846578, 1.16027671, 0.…
 $ spei_12     <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 0.679002…
 $ spei_24     <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, … 
$ spei_3      <dbl> NA, NA, -0.38663839, 1.12752241, 0.95519894, 0.76263… 
$ spei_6      <dbl> NA, NA, NA, NA, NA, 0.7025135, 0.7972795, 0.9579071,… 
$ spi_1       <dbl> -1.30267102, -1.68193728, 1.71027690, 0.86320850, 0.… 
$ spi_12      <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 0.5382415, 0… 
$ spi_24      <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, … 
$ spi_3       <dbl> NA, -1.663633823, -0.470923200, 0.859218299, 0.73609… 
$ spi_6       <dbl> NA, NA, NA, NA, 0.37467906, 0.51499903, 0.69652975, … 
$ spei_1_cat  <chr> "moderada", "moderada", "sin", "sin", "sin", "sin", … 
$ spei_12_cat <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "sin", "… 
$ spei_24_cat <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, … 
$ spei_3_cat  <chr> NA, NA, "sin", "sin", "sin", "sin", "sin", "sin", "s… 
$ spei_6_cat  <chr> NA, NA, NA, NA, NA, "sin", "sin", "sin", "sin", "sin… 
$ spi_1_cat   <chr> "moderada", "severa", "sin", "sin", "sin", "sin", "s… 
$ spi_12_cat  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "sin", "sin"… 
$ spi_24_cat  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, … 
$ spi_3_cat   <chr> NA, "severa", "sin", "sin", "sin", "sin", "sin", "si… 
$ spi_6_cat   <chr> NA, NA, NA, NA, "sin", "sin", "sin", "sin", "sin", "…
```

```r
data |> distinct(unit)
             unit
1 distrito_censal
2         cuencas
3      subcuencas
4   subsubcuencas
5        regiones
6      provincias
7         comunas
```

**Comment by jbkunst** [comment]
@frzambra  

Entiendo que _más datos_ es mejor, sin embargo al agregar variables discretas producen impactos en tiempos de desarrollo que debemos evaluar (mañana viernes), pues nunca se habian conversado que existiría las versiones categorias de las variables (al menos no lo recuerdo 😢) , por lo que hasta ahora todo está programado para variables continuas de acuerdo al primer data set dummy que comenzamos a trabajar. 

Lo migramos a otro issue dado que este en particular se refiere a origen de datos?

El tema es que producen casuísticas  que se deben conversar, por ejemplo:
1. Como mostramos la info en el _mini gráfico_ ? 
2. La lista de _Variables_ no quedaría muy extensa? Habría que agregar un selector si quiere la versión continua o categórica? Se haría más grande el menu de controles.
3. En el reporte, como comparamos los valores categóricos respecto a los otros años? Me imagino un heartmap. es lo usual?
4. Lo de las version de las variables categóricas no sería redundante  dado que @fabian199827  solicita en #23 colorear de acuerdo a estos niveles? Me confirman si es lo mismo?

![image](https://user-images.githubusercontent.com/56481/231928557-c71ad1f5-be79-4615-9f8d-2a677b650b01.png)

Lo hablamos!

**Comment by frzambra** [comment]
Si, de acuerdo, conversemoslo hoy. No es necesario tener las categorias para todas las fechas, solo para la que se está consultando, por lo que se puede hacer on the fly. No necesario incluirlo en la BBDD.
