### ISSUE TITLE
Descarga de datos

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#22]
Favor corregirme si es necesario, esto lo conversamos con Francisco pero corrígeme para ver si capté bien la idea @frzambra.

Con el arreglo de Leaflet  (agregandolo a la ventana de "mapa"). En vez de que diga "configuración" se debe reemplazar con una opción para descargar datos brutos, en formato Excel o .csv de la información seleccionada en la ventana de filtros. A continuación presento la imagen original y como debe quedar.

![imagen](https://user-images.githubusercontent.com/128641014/229903270-26a9c9d1-eb58-40bf-8811-1a8825cd521f.png)
Figura 1. Estado original de la página.

![imagen](https://user-images.githubusercontent.com/128641014/229905783-2e54e2c5-0948-4d9a-8fcf-f029f2b3c991.png)
Figura 2.  Opción para descargar los datos.

**Comment by frzambra** [comment]
Si, la pestaña de configuración tenía la función de poder seleccionar el mapa de referencia. Creo que lo que es de interés, es poder descargar los datos. En este caso se deberían poder descargar para la variable seleccionada, cada unidad (región, comuna, provincia, cuenca, etc) que se encuentre dentro de la macro zona seleccionada.

**Comment by fabian199827** [comment]
@jbkunst Esto es lo que conversamos el día de la reunión en cuanto a la descarga de los datos.
