### ISSUE TITLE
Niveles de los indicadores de sequía

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#23]
En vez de que aparezca el valor numérico de SPEI y SPI identificar de la siguiente forma:

SPI:
Anormalmente seco (amarillo): -0,5 a -0,7
Sequía moderada (beighe): -0,8 a -1,2
Sequía severa (naranjo): -1,3 a -1,5
Sequía extrema (rojo): -1,6 a -1,9
Sequía excepcional (burdeo): -2 o menos 

![imagen](https://user-images.githubusercontent.com/128641014/231836634-e9c46d51-ca1e-4327-9ff9-e063edafc8af.png) ![imagen](https://user-images.githubusercontent.com/128641014/231836743-c627ce3c-a44a-4559-b1cd-4aabbcf1b550.png)

Fuente: https://droughtmonitor.unl.edu/About/AbouttheData/DroughtClassification.aspx

SPEI:
![imagen](https://user-images.githubusercontent.com/128641014/231836113-0ab902bd-ab14-41b4-ab1d-9e97a6eafd24.png)
Fuente: https://www.researchgate.net/figure/SPEI-drought-index-categories_tbl1_283244485#:~:text=SPEI%20has%20positive%20and%20negative,(Vicente%2DSerrano%20et%20al.

Toda esta información debe reemplazar lo que está acutualmente en este lugar:
![imagen](https://user-images.githubusercontent.com/128641014/231837735-f143a39c-1ea1-440d-80f9-676b6d322bbd.png)

**Comment by jbkunst** [comment]
@frzambra  puntos de corte, el `cut(...)`

**Comment by jbkunst** [comment]
@fabian199827  que ocurre cuando un SPI es por ejemplo -0.3? lacategoria más alta es desde -0,7 a -0,5. 

![image](https://user-images.githubusercontent.com/56481/236349862-5079aaa3-57a1-4ea9-8b44-750a06d98159.png)

**Comment by jbkunst** [comment]
SPI, SPEI "No disponible" es "sin sequía", color blanco.

**Comment by frzambra** [comment]
@jbkunst  Abajo está la paleta de colores para los indicadores de sequía y las categorias de acuerdo a los percentiles.

```r
palette <- c('#730000','#E60000','#FFAA00','#FFD37F','#FFFF00','#FFFFFF','#8CCDEF','#00BFFF','#1D90FF','#4169E1','#0000FF')
perc <- c(0,.02,.05,.1,.2,.3,.7,.8,.9,.95,.98,1) #percentiles para categorias

#ejemplo con una distribución normal
set.seed(123)
x <- rnorm(100)
x_cut <- cut(x,quantile(x,perc),include.lowest = TRUE)
```

**Comment by jbkunst** [comment]
Duda @frzambra , esto es en base al histórico? Mi duda es la siguiente: Si tomo dos periodos distintos (por ej, desde 2009 a 2022 y luego del 2018 a 2022) un valor (ej 0.04) podría quedar en distintas categorias dependiendo de la distribución del periodo de tiempo que estoy mirando. Eso es correcto?

**Comment by frzambra** [comment]
@jbkunst  muy buen punto. En el caso de los indicadores de sequía se debe considerar el periodo histórico. Los índices de sequía se calculan en base a un periodo extenso > 20 años.  Por lo que los valores y clases que se deberían mostrar son los del indicador en base a los valores históricos. El usuario puede elegir un periodo acotado para ver los indicadores (que muestran valores respecto al histórico).

**Comment by jbkunst** [comment]
@frzambra Entiendo, me queda claro. Por tanto, es posible que mue indiques para cada SPI, SPEI los valores que debo cortar? Los podría obtener @joaquinRiquelme?

**Comment by fabian199827** [comment]
@frzambra  dar los valores de los percentiles que correspondan.

**Comment by frzambra** [comment]
@jbkunst dejé un ejemplo de la generación de la paleta de colores con los correspondientes colores revisar el script [acá](https://github.com/ODES-Chile/odes-unidades-shiny-app/blob/main/R/04_ejemplo_mapa_niveles_sequia.R)

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/4713428/c299530c-498b-4203-8d2b-8232c4d382e1)

Esto es lo que deberiamos utilizar para todos los indicadores de sequía. En el reporte debería aparecer la clase.

@jbkunst @fabian199827 cambié la prioridad de este issue a `alta`, esto agradecería mucho si lo podemos solucionar de aquí al martes.

**Comment by jbkunst** [comment]
@frzambra 

Te parece calcular los quantiles históricos para cada unidad? Así el resultado de los cuantiles siempre será el mismo _independiente_ del periodo/mes seleccionado.

![image](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/56481/c9df2c17-02a8-4b30-b5ae-092c12cc86e6)

**Comment by frzambra** [comment]
> @jbkunst dejé un ejemplo de la generación de la paleta de colores con los correspondientes colores revisar el script [acá](https://github.com/ODES-Chile/odes-unidades-shiny-app/blob/main/R/04_ejemplo_mapa_niveles_sequia.R)
> 
> ![imagen](https://user-images.githubusercontent.com/4713428/244951837-c299530c-498b-4203-8d2b-8232c4d382e1.png)
> 
> Esto es lo que deberiamos utilizar para todos los indicadores de sequía. En el reporte debería aparecer la clase.
> 
> @jbkunst @fabian199827 cambié la prioridad de este issue a `alta`, esto agradecería mucho si lo podemos solucionar de aquí al martes.

Hay que darle una segunda vuelta a esto, ya que en este caso consideré la variación espacial de una fecha para todas las unidades y debería ser la variación temporal por unidad.

**Comment by frzambra** [comment]
> @frzambra
> 
> Te parece calcular los quantiles históricos para cada unidad? Así el resultado de los cuantiles siempre será el mismo _independiente_ del periodo/mes seleccionado.
> 
> ![image](https://user-images.githubusercontent.com/56481/244957041-c9df2c17-02a8-4b30-b5ae-092c12cc86e6.png)

@jbkunst Crear columnas nuevas con los valores de los cuantiles por unidad? Por ejemplo, "spei_1_q" para quantile del SPEI-1 .

**Comment by frzambra** [comment]
@jbkunst subí la tabla de la BBDD con las columnas _q que corresponden a las clases de sequía. Estas son de `S4:S0,N,H0:H4`: esto es de Sequía 4 a Sequía 0, normal, humedo 0 a humedo 4. La idea es como lo que aparece en la imagen

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/4713428/47b32bcb-6e4f-48bd-a9ee-5dfe6d7f28ee)

De esta manera quedarian los colores fijos de acuerdo al nivel de sequía de cada unidad para la fecha.

**Comment by frzambra** [comment]
@jbkunst ví tu ws, pero creo que tu estas calculando los 12 cuantiles para cada unidad. Lo que necesitamos es saber a qué cuantil pertenece - de los definidos- el valor que tiene la unidad en cada uno de los meses.

El script que uso yo es:

```r
f <- \(x,rev = FALSE) {
  c <- rep(NA,length(x))
  
  if (!all(is.na(x))){
    perc <- c(0,.02,.05,.1,.2,.3,.7,.8,.9,.95,.98,1)
    levs <- c(paste0('S',4:0),'N',paste0('H',0:4))
    q <- quantile(x,perc,na.rm = TRUE) |> unique()
    c <- cut(x,q,include.lowest = TRUE)
    n <- levels(c) |> length()
    
    levels(c) <- if(rev) rev(levs[1:n]) else levs[1:n]
  }
  c
}

data_unida_q <- data_unida |> 
  group_by(code) |> 
  mutate(across(matches('spi|spei|zndvi|sma'),f,.names = "{.col}_q")) |> 
  mutate(across(matches('eddi'),.fns = \(x) f(x,rev = TRUE),.names = "{.col}_q")) 
```
El resultado de esto, sólo seleccionando las nuevas columnas de cuantiles creadas es:

```r
> data_unida_q |> select(code:date,matches('_q')) |> slice_tail()
# A tibble: 5,079 × 24
# Groups:   code [5,079]
   code  unit   date       tasmax_q sma_100cm_q spei_1_q spei_12_q spei_24_q spei_3_q spei_36_q spei_6_q spi_1_q spi_12_q spi_24_q spi_3_q spi_36_q spi_6_q
   <chr> <chr>  <date>     <fct>    <fct>       <fct>    <fct>     <fct>     <fct>    <fct>     <fct>    <fct>   <fct>    <fct>    <fct>   <fct>    <fct>  
 1 01    regio… 2023-05-01 N        H0          S1       N         N         N        N         S0       H0      S1       S4       N       S3       S1     
 2 010   cuenc… 2023-05-01 N        H2          S0       S0        N         S1       N         S1       H0      S4       S4       S1      S1       S3     
 3 0100  subcu… 2023-05-01 N        H0          S1       S1        S0        S2       N         S1       N       S4       S3       S1      N        S4     
 4 01000 subsu… 2023-05-01 N        H0          S1       S1        S0        S2       N         S1       N       S3       S3       S1      N        S3     
 5 01001 subsu… 2023-05-01 N        H0          S1       S1        S0        S2       N         S2       N       S4       S2       S1      H0       S4     
 6 0101  subcu… 2023-05-01 N        H1          S1       S1        S0        S2       N         S2       N       S4       S3       S1      N        S4     
 7 01010 subsu… 2023-05-01 N        H1          S1       S1        S0        S2       N         S2       N       S4       S3       S1      N        S4     
 8 0102  subcu… 2023-05-01 N        H2          S0       S1        S0        S2       S0        S2       N       S3       S4       S1      S1       S3     
 9 01020 subsu… 2023-05-01 N        H2          N        S1        S0        S2       N         S1       N       S4       S3       S1      S0       S4     
10 01021 subsu… 2023-05-01 N        H2          S0       S1        S0        S2       N         S2       N       S3       S4       S0      S1       S2  
```
Lo niveles son `S4, S3, S2, S1, S0, N, H0, H1, H2, H3, H4` para los quantiles c(0,.02,.05,.1,.2,.3,.7,.8,.9,.95,.98,1), en el caso de EDDI (por la carecteristica del índice) es al reves, por eso la función tiene un argumento `rev`.

![image](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/4713428/686abec5-ebcb-428b-8dec-ed2e2520186e)

**Comment by frzambra** [comment]
@jbkunst subí una tabla nueva como prueba, tiene los mismos datos que la anterior más los valores de la categoría

```r
data_clima_sequia <- tbl(con, "data_clima_sequia_q")
data_clima_sequia |> select(matches('_q'))
# Source:   SQL [?? x 21]
# Database: postgres  [shiny@198.199.65.25:5432/shiny]
   tasmax_q sma_100cm_q spei_1_q spei_12_q spei_24_q spei_3_q spei_36_q spei_6_q spi_1_q spi_12_q spi_24_q spi_3_q spi_36_q spi_6_q zndvi_q eddi_1_q
   <chr>    <chr>       <chr>    <chr>     <chr>     <chr>    <chr>     <chr>    <chr>   <chr>    <chr>    <chr>   <chr>    <chr>   <chr>   <chr>   
 1 N        N           NA       NA        NA        NA       NA        NA       NA      NA       NA       NA      NA       NA      NA      NA      
 2 H2       H1          S0       NA        NA        NA       NA        NA       H1      NA       NA       NA      NA       NA      NA      N       
 3 H1       N           S0       NA        NA        N        NA        NA       S1      NA       NA       S0      NA       NA      NA      N       
 4 N        H4          S0       NA        NA        S0       NA        NA       S0      NA       NA       S0      NA       NA      NA      N       
 5 N        N           S0       NA        NA        S0       NA        NA       S1      NA       NA       S3      NA       NA      NA      N       
 6 S1       N           S0       NA        NA        S1       NA        S0       H0      NA       NA       S0      NA       S0      NA      N       
 7 S1       S1          S0       NA        NA        S0       NA        S0       N       NA       NA       N       NA       S0      NA      N       
 8 S2       H4          N        NA        NA        S0       NA        S0       H1      NA       NA       H0      NA       H0      NA      H1      
```

**Comment by jbkunst** [comment]
@frzambra  efectivamente lo que te mostré es calcular los cuantiles, lo que me faltó agregarte es la aplicación para el cálculo https://github.com/ODES-Chile/odes-unidades-shiny-app/blob/main/R/97_dquantiles.R#LL38C1-L66C27

Pensaba por que calcular _tooodos_ los valores y no calcular a _demanda_, pensaba que sería más óptimo. 
Trabajaré con lo que tienes entonces. 

Que tan complicado es subir los valores numéricos 1 a 11 en lugar en lugar de la etiqueta N, H2, H1?

**Comment by frzambra** [comment]
@jbkunst ojo, que esta coloración NO es sólo para el semáforo, sino que para colorear todo el mapa (todas las unidades) cuando se cambie a una fecha determinada. La idea es que cada unidad tenga un color fijo de acuerdo a su categoria (valor) para cada mes.

Cambiar los valores de 1 a 11 no hay problema

**Comment by jbkunst** [comment]
@frzambra  Si, está claro que es tanto para los colores del map/corpleta como el del semaforo en el reporte de sequía.

Gracias por cambiar lso valores, es más liviano en términos de datos y más facil en su uso en la app.

**Comment by frzambra** [comment]
@jbkunst @joaquinRiquelme están actualizados los datos con las categorias.
