### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#24]
Se debe agregar una extensión de google analytics para poder tener una estadística del uso de la página web

**Comment by jbkunst** [comment]
ODES tiene usuario de google analitycs para que me den el código que debo incluir en el sitio?

https://analytics.google.com/analytics/web/#

**Comment by frzambra** [comment]
@jbkunst acá está la etiqueta de google analytics

```js
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-CYG993XQRT"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-CYG993XQRT');
</script>
```
