### ISSUE TITLE
Localizador de posición y buscador de ubicación

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#25]
Agregar un localizador de posición y una opción para buscar ubicaciones como en este ejemplo de google maps. Este ícono debe permitir encontrar la ubicación de donde se abrió la pagina web: 
![imagen](https://user-images.githubusercontent.com/128641014/232050485-e4a35c4d-80bf-4ebf-8300-96de0dcc54b7.png)

Por otro lado el buscador de ubicación es para identificar en el mapa udidades administrativas en particular, quizas alguna comuna, región, distrito, etc. Asi como en el ejemplo de google maps, pero en vez de buscar direcciones específicas, buscar las unidades administrativas que comprenden al mapa de ODES:
![imagen](https://user-images.githubusercontent.com/128641014/232051148-5cf47a97-9dcc-4f3f-9995-d9fd9e56fce8.png)

Esta es mi idea de como podría quedar en odes:
![imagen](https://user-images.githubusercontent.com/128641014/231859416-f657cd65-c9e8-4863-9fcd-8ec278bbecb8.png)

**Comment by jbkunst** [comment]
don @fabian199827 puede detallar un poco más el funcionamiento? que son las opciones? que sucede cuando hago click en alguna opción?

don @frzambra , tiene algún ejemplo de la implementación de esta _feature_? Las opciones todas las unidades de la unidad administrativa seleccionada me imagino.

**Comment by fabian199827** [comment]
Disculpa @jbkunst aquí di mas detalle en el issue, lo actualicé con mayor detalle. Saludos, nos vemos!

**Comment by jbkunst** [comment]
don @frzambra  comparte código/función de leaflet.extras

**Comment by frzambra** [comment]
```r
leaflet('map') %>%
    #mapview()@map %>% 
      addSearchOSM(options = searchOSMOptions(
        textErr = "Ubicación no encontrada", textCancel = "Cancelar",
        textPlaceholder = "Buscar...",
        position = 'topleft')) |>
       addEasyButton(easyButton(
           icon="fa-crosshairs", title="Mi ubicación",
           onClick=JS("function(btn, map){ map.locate({setView: true}); }"))
```
