### ISSUE TITLE
Reporte

### ISSUE THREAD

**Issue by jbkunst** [ODES-Chile/odes-unidades-shiny-app#26]
KPI
- SPEI 12    ACTUAL, comparado peor y mejor histórico 
- EDDI       ACTUAL, comparado peor y mejor histórico   
- SMDI       ACTUAL, comparado peor y mejor histórico         
- VEGETACION ACTUAL, comparado peor y mejor histórico

Valuebox, sparklines

**Comment by jbkunst** [comment]
Existe reporte, creo que faltarían algunas  cosas:

- Los datos que se comentaron en un principio: EDDI, SMDI, VEGETACION:
- Puntos de cortes para indicar el estado actual. Cuando indicar que el valor acrtual es el pesperado o está en alerta.


![image](https://user-images.githubusercontent.com/56481/236274131-f60e7c74-961d-40fc-80e6-db6fb563b53e.png)

**Comment by jbkunst** [comment]
@fabian199827 @frzambra 

Perdón: ¿Cual era la división de las variables? , variables de squia (spei, spi) y variables meteorológicas?

**Comment by fabian199827** [comment]
Si, pero quizás queda mejor:
1) Indicadores de Sequía (en vez de variables de sequía)
2) Variables Meteorológicas

@frzambra qué te parece?

**Comment by jbkunst** [comment]
Se reagrupan variables:
![image](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/56481/b18bbcdf-df9e-48c8-acd0-559e8c481abb)

**Comment by fabian199827** [comment]
@jbkunst ahora no aparece de esta forma el selector de variables. aparece asi:

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/3da8ad14-be01-4fc2-9783-7cef415e4e94)

**Comment by fabian199827** [comment]
Agregar opción de guardar/descargar reporte como PDF

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/940c23f2-342e-4740-aaaa-90b0a24ffde3)

**Comment by fabian199827** [comment]
@jbkunst conversé con @frzambra y me señaló que podríamos cambiar la opción de "Generar reporte" en el popup 
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/bc35a856-2f08-4ce7-bd87-e696cb6fae36)
por una opción que diga "Reporte de sequía" y que se genere el mismo reporte que está actualmente pero sólo con los indicadores de sequía que indicará Francisco 

Por otro lado, para ver el gráfico que se genera en función de la variable:
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/e3cae456-fb15-4e79-8963-fac88d91e61d)

Que se genere agregrando una opción bajo el mini gráfico que diga algo así como "Reporte variable" o "Reporte anual" (Discutámolos el viernes para ver cómo identificar esta función)

**Comment by fabian199827** [comment]
Opción para agregar información en reporte:
La idea es que cuando se le haga clic en la "i" se abra una ventanita donde se explique lo que significa el indicador. Yo haré el texto descriptivo
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/30ce0932-4424-47a5-b029-ddea81d5ef0c)

SPEI12
Este índice captura la anomalía de la precipitación menos la evapotranspiración en 12 meses junto con la severidad de la sequía según su intensidad y duración, también permite detectar el inicio y el final de los periodos de sequía. 

EDDI12
Este indicador señala la anomalía de la demanda evaporativa de agua que tiene la atmósfera en un periodo de 12 meses, es decir qué tanto ha cambiado las. (REVISAR)

zcSM
Este indicador de humedad de suelo, muestra la anomalía que ha presentado la humedad del suelo acumulada a 1m de profundidad en un periodo de 12 meses. (REVISAR)

zcNDVI
Este índice vegetacional permite capturar la anomalía que ha presentado la vegetación en un periodo de 12 meses. (REVISAR) 

PONER REFERENCIAS

SPEI
Vicente-Serrano, S. M., Beguería, S., & López-Moreno, J. I. (2010). A multiscalar drought index sensitive to global warming: The Standardized Precipitation Evapotranspiration Index. Journal of Climate, 23(7), 1696-1718. 

EDDI
Michael Hobbins, Andrew Wood, Daniel McEvoy, Justin Huntington, Charles Morton, James Verdin, Martha Anderson, and Christopher Hain (June 2016): The Evaporative Demand Drought index: Part I – Linking Drought Evolution to Variations in Evaporative Demand. J. Hydrometeor., 17(6),1745-1761. [doi:10.1175/JHM-D-15-0121.1](http://dx.doi.org/10.1175/JHM-D-15-0121.1).

Daniel J. McEvoy, Justin L. Huntington, Michael T. Hobbins, Andrew Wood, Charles Morton, James Verdin, Martha Anderson, and Christopher Hain (June 2016) The Evaporative Demand Drought index: Part II – CONUS-wide Assessment Against Common Drought Indicators. J. Hydrometeor., 17(6), 1763-1779. [doi:10.1175/JHM-D-15-0121.1](http://dx.doi.org/10.1175/JHM-D-15-0121.1).

zcNDVI
Rouse, J. W., Haas, R. H., Schell, J. A., Deering, D. W., & Harlan, J. C. (1974). Monitoring the Vernal Advancement and Retrogradation (Greenwave Effect) of Natural Vegetation. Remote Sensing Center, 1(September 1972), 48–62. https://ntrs.nasa.gov/search.jsp?R=19750020419 2020-03-22T20:18:24+00:00Z j

**Comment by fabian199827** [comment]
En el selector de intervalos de fecha, la linea roja que aparece abajo es sólo de la variable de "anomalía de la humedad de suelo a 1m"
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/459ccae4-0e0a-42e7-9bd7-86f93f544359)

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/0a4f6a83-965c-49d3-a63a-a775424ea7ec)

**Comment by jbkunst** [comment]
Se ha implementado un tooltip html. Puse el ícono abajo a la derecha para que el índice/texto aparezca primero sin perder protagonismo.

Moverlo hacia arriba costaría  un poco más, por que `value_box` permite agregar contenido extra (aparte de lo principal: texto y número) solo abajo,

![image](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/56481/d61ffdac-84d1-4a08-a92f-4b2293f2de6d)
