### ISSUE TITLE
Sin datos

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#27]
No aparecen datos en las variable precipitación, demanda evapotranspirativa de la atmósfera, temperatura mínima, spei 1, 3, 6, 9, 12, 24, spi 1, 3, 6, 9, 12, 24 

En todas las variables antes mencionadas ahora no aparecen datos y se ven de esta forma:

![imagen](https://user-images.githubusercontent.com/128641014/232887202-eec3bc20-3870-4108-ae7e-e6d0c726c7d7.png)

**Comment by jbkunst** [comment]
Recuerda que @frzambra  dijo que hay datos desde junio 2019 hacia atrás... por defecto se muestra la ultima fecha de la tabla, pero en este caso no se tienen datos. Don @frzambra mecionaría que cortaría la tabla de la bbdd.

**Comment by jbkunst** [comment]
Si gustas dejas _abierto_ el issue para que se cierre cuando Francisco actualice la tabla de la bbdd.

**Comment by fabian199827** [comment]
Okey

**Comment by jbkunst** [comment]
Fije mostrar hasta 2019-06.

![image](https://user-images.githubusercontent.com/56481/235037656-6454c6b5-f6ce-4b80-9f94-221020c11aa1.png)

**Comment by fabian199827** [comment]
@jbkunst debemos cambiar los años del texto bajo el gráfico

![imagen](https://user-images.githubusercontent.com/128641014/235187466-4ef44444-258f-43d9-8787-da8217e0aeb0.png)
debe decir: 

Para preciítación:
"Precipitación acumulada mensual, desde 1979 a 2019. Este gráfico permite comparar la cantidad de precipitación entre distintos años."

Para demanda evapotranspirativa de la atmósfera:
Evapotranspiración promedio mensual desde 1979 a 2019. Este gráfico permite comparar la evapotranspiración en distintos años.

Para temperatura:
Temperatura promedio mensual desde 1979 a 2019. Este gráfico permite comparar la variación de temperaturas en distintos años.

Para temperatura minima:
Temperatura mínima promedio mensual desde 1979 a 2019. Este gráfico permite comparar la variación de temperaturas en distintos años.

Para temperatura máxima:
Temperatura máxima promedio mensual desde 1979 a 2019. Este gráfico permite comparar la variación de temperaturas en distintos años.

SPEI 1
Índice de sequía SPEI. Este índice indica la anomalía de la precipitación menos la evapotranspiración en 1 mes entre los años 1979 y 2019.

SPEI 3
Índice de sequía SPEI. Este índice indica la anomalía de la precipitación menos la evapotranspiración en 3 mes entre los años 1979 y 2019.

 SPEI 6
Índice de sequía SPEI. Este índice indica la anomalía de la precipitación menos la evapotranspiración en 6 mes entre los años 1979 y 2019.

SPEI 9
Índice de sequía SPEI. Este índice indica la anomalía de la precipitación menos la evapotranspiración en 9 mes entre los años 1979 y 2019.

SPEI 12
Índice de sequía SPEI. Este índice indica la anomalía de la precipitación menos la evapotranspiración en 12 mes entre los años 1979 y 2019.

SPEI 24
Índice de sequía SPEI. Este índice indica la anomalía de la precipitación menos la evapotranspiración en 24 mes entre los años 1979 y 2019.

SPI 1
Indice de sequía SPI. Este índice indica la anomalía de la precipitación acumulada en 1 mes entre los años 1979 y 2019.

SPI 3
Indice de sequía SPI. Este índice indica la anomalía de la precipitación acumulada en 3 mes entre los años 1979 y 2019.

SPI 6
Indice de sequía SPI. Este índice indica la anomalía de la precipitación acumulada en 6 mes entre los años 1979 y 2019.

SPI 9
Indice de sequía SPI. Este índice indica la anomalía de la precipitación acumulada en 9 mes entre los años 1979 y 2019.

SPI 12
Indice de sequía SPI. Este índice indica la anomalía de la precipitación acumulada en 12 mes entre los años 1979 y 2019.

SPI 24
Indice de sequía SPI. Este índice indica la anomalía de la precipitación acumulada en 24 mes entre los años 1979 y 2019.
