### ISSUE TITLE
Región de Valparaíso

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#28]
Quizás este issue tiene que ver con el issue 9 y 10, sin embargo prefiero hacer uno a parte para describirlo mejor. En algunos casos cuando se selecciona macrozona centro + alguna unidad administrativa, la región de Valparaiso queda fuera. A continuación documento esta situación:

1) Macrozona Central + Regiones: **No** se incluye Valparaíso (Figura 1)
![imagen](https://user-images.githubusercontent.com/128641014/233400304-fd3542a9-d18e-42d7-bb4e-ea12796c28a8.png)
Figura 1.

2) Mcrozona Central + Provincias: **Si** se incluye Valparaíso (Figura 2)
![imagen](https://user-images.githubusercontent.com/128641014/233400600-fd67e3c4-39c9-4704-9275-9aeafa6af49b.png)
Figura 2.

3) Mcrozona Central + Comunas: **S**i se incluye Valparaíso (Figura 3)
![imagen](https://user-images.githubusercontent.com/128641014/233401041-da7b7cf7-edd8-4b7a-8e60-d03c556b736d.png)
Figura 3

4) Macrozona + distrito censal: **caida de página** (Figura 4)
![imagen](https://user-images.githubusercontent.com/128641014/233402293-527b4b24-153e-4fff-9a16-1f0c3ea2c586.png)
Figura 4.

5) Macrozona + cuenca: **Si** se incluye Valparaíso (Figura 5)
![imagen](https://user-images.githubusercontent.com/128641014/233402947-eb834781-8d57-4c3e-922b-ab1e9aed8ac1.png)
Figura 5.

6) Macrozona + subcuencas: **Si** se incluye la Región de Valparíso (Figura 6)
![imagen](https://user-images.githubusercontent.com/128641014/233403285-83fd68af-daa0-4022-88d9-27b5435c5da6.png)
Figura 6.

7) Macrozona + subsubcuencas: **Si** se incluye Valparaíso (Figura 7)
![imagen](https://user-images.githubusercontent.com/128641014/233403656-6fc8e7d9-59c5-4ab6-8869-5e63d9747ee6.png)
Figura 7.

**Comment by jbkunst** [comment]
[unidades_sin_macrozona.xlsx](https://github.com/ODES-Chile/odes-unidades-shiny-app/files/11290702/unidades_sin_macrozona.xlsx)

**Comment by fabian199827** [comment]
@jbkunst @frzambra dejo por acá las unidades sin macrozona corregidas.

[unidades_sin_macrozona_corregida.xlsx](https://github.com/ODES-Chile/odes-unidades-shiny-app/files/11312395/unidades_sin_macrozona_corregida.xlsx)


Aquí indentifico las unidades con la macrozona que corresponde, quedo atento ante cualquier corrección.

**Comment by jbkunst** [comment]
se corrigió manualmente en https://github.com/ODES-Chile/odes-unidades-shiny-app/commit/44089c5b01c52bfdef610b1ed55d18d10c642eaf

**Comment by fabian199827** [comment]
@jbkunst @frzambra Encontré un error que tiene que ver con este mismo issue, lo presento a continuación:

**Unidades administrativas no están en la macrozona que corresponde.**

Provincia de Valparaíso se agrega a la macrozona norte chico, siendo que pertenece a la macrozona central

![imagen](https://user-images.githubusercontent.com/128641014/234342042-75d7c4c2-c4cc-4a6f-a7c1-c9b35784ab60.png)

Comuna de Valparaíso se agrega a la macrozona norte chico, siendo que pertenece a la macrozona central

![imagen](https://user-images.githubusercontent.com/128641014/234342088-522fee26-f6c4-49aa-8ae6-7f2737437609.png)

Comunas de coronel, Chiguayante y florida se agrega a la macrozona  central y pertenecen a la macrozona sur

![imagen](https://user-images.githubusercontent.com/128641014/234342193-119ba155-f67d-4d42-bc45-f110a8b1fd48.png)

@jbkunst aquí adjunto porsiacaso un excel con la macrozona a la que pertenece cada unidad. Creo que se puede arreglar de forma manual. Corrígeme siesque me equivoco. Lo hice de la misma forma que lo hicimos con las unidades sin macrozona asignada Saludos
[correccion_unidades_mal_ubicadas.xlsx](https://github.com/ODES-Chile/odes-unidades-shiny-app/files/11344790/correccion_unidades_mal_ubicadas.xlsx)
