### ISSUE TITLE
Error en mini gráfico en indices de sequía (SPEI y SPI)

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#29]
El gráfico de líneas se visualiza de forma errática (Figura 1), esta situación se repite con casi todas las variables SPEI dentro de la misma unidad administrativa seleccionada. Me voy a la opción de descargar datos y se visualizan datos de meses dupilicados (Figura 2). Por otro lado existen ventanas de tiempo sin datos (figura 3) cuando se descargan esos datos, se visualizan como se ven en la figura 4.

Los indicadores con mes duplicado: 
Todos los SPEI y SPI + Provincias.
Esto es para la provincia Río Loa Antofagasta pero se debe repetir para varias provincias.
Todos los SPEI y SPI + cuencas
Esto es para la La cuenca del Río Aconcagua Petorca pero se debe repetir para varias cuencas.

Indicadores con falta de datos: Todos los SPEI y SPI +  Provincias.
Esto es para la provincia Río Loa Antofagasta pero se debe repetir para varias provincias.

![imagen](https://user-images.githubusercontent.com/128641014/234876135-24f5e977-aad9-4b4d-af3e-2629d041d400.png)
Figura 1

![imagen](https://user-images.githubusercontent.com/128641014/234879317-f48284de-b367-4358-ab0c-075cf5eaf082.png)
Figura 2

![imagen](https://user-images.githubusercontent.com/128641014/234892437-8f7de3c9-b76d-444c-8213-ec8e77d8a909.png)
Figura 3

![imagen](https://user-images.githubusercontent.com/128641014/234902445-67c60a88-7cad-4f34-9829-f5872873fc8f.png)
Figura 4

**Comment by jbkunst** [comment]
Existen fechas duplicadas, por ejemplo:

``` r
sql_con <- function() {
    pool::dbPool(
      drv = RPostgres::Postgres(),
      dbname = "shiny",
      host = Sys.getenv("HOST"),
      user = "shiny",
      password = Sys.getenv("SHINY_PSQL_PWD")
    )
  }

suppressWarnings(library(tidyverse))

d <- tbl(sql_con(), "data_clima_sequia") |> 
  filter(code == "022") |> 
  filter(between(year(date), 2016, 2018)) |> 
  select(date, spei_12) |> 
  arrange(date) |> 
  collect()

d |> 
  count(date)
#> # A tibble: 36 × 2
#>    date           n
#>    <date>     <int>
#>  1 2016-01-01     2
#>  2 2016-02-01     2
#>  3 2016-03-01     2
#>  4 2016-04-01     2
#>  5 2016-05-01     2
#>  6 2016-06-01     2
#>  7 2016-07-01     2
#>  8 2016-08-01     2
#>  9 2016-09-01     2
#> 10 2016-10-01     2
#> # … with 26 more rows

ggplot(d, aes(date, spei_12)) +
  geom_line() +
  geom_point()
```

![](https://i.imgur.com/0TbGmuz.png)

<sup>Created on 2023-04-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by joaquinRiquelme** [comment]
Hola, creo que encontré donde está el problema.
Cuando se hace el filtro con 
 filter(code == "022") |> 
se pide la unidad que tenga el código 022, pero no se especifica el tipo de unidad. Esto genera que se grafiquen los datos de las unidades 022 cuenca y provincia.

![image](https://user-images.githubusercontent.com/43077799/236071425-eb4a4b30-8ae4-4433-9c80-e0b870f9e7b8.png)

Para solucionar el problema se debería agregar otra condición al filtro, ejemplo:

filter(unit=="cuencas")

Espero esto pueda solucionar los datos duplicados. Seguiré revisando los datos faltantes.

Saludos

**Comment by jbkunst** [comment]
Gracias @joaquinRiquelme , tiene todo el sentido. Agregué el filtro por unidad! Cuando pueda, le agradecería que revise algunos casos don @fabian199827

**Comment by fabian199827** [comment]
@jbkunst @joaquinRiquelme  Súper!! Ahora replico la misma combinación y el gráfico se ve bien (Figura 1) 
![imagen](https://user-images.githubusercontent.com/128641014/236202071-0c6cab1b-359a-41ba-9d39-0528995075ea.png)
Figura 1

Sin embargo  hay años para atrás que no se ven los indicadores, osea se ven vacíos. Hasta el año 1999 se logra ver la línea continua y cuando voy hacia atrás se ven vacíos (Figura 2 y 3)

![imagen](https://user-images.githubusercontent.com/128641014/236202345-3007c0a9-b05b-4872-9e59-16f2d0bc4391.png)
Figura 2. Línea continua

![imagen](https://user-images.githubusercontent.com/128641014/236204028-537ddfc4-d95e-4fe6-972f-7ed9c5f7e22a.png)
Figura 3. Se descontinúa la línea

**Comment by joaquinRiquelme** [comment]
[reporte.pdf](https://github.com/ODES-Chile/odes-unidades-shiny-app/files/11410798/reporte.pdf)

Hola @frzambra , va reporte de datos faltantes, creo que los datos faltantes estan en todas las unidades y faltan datos de SPEI mas que de SPI. Por otra parte, mientras mayor sea el horizonte de evaluación del indice menos datos faltan.
No encontré algún patrón que indique que exista algun error sistemático, lo que creo es que de alguna manera se indetermina el valor, pero para ir más allá necesitaría ver el algoritmo.

Espero te sea de alguna ayuda.
Saludos
