### ISSUE TITLE
nombre de planilla de descarga de datos

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#30]
Cuando se descarguen las planillas de datos, que se visuelice el nombre de la zona que se descargó y el año. Actualmente se ve así:
![imagen](https://user-images.githubusercontent.com/128641014/234923113-abf8b458-6781-4e02-8052-706c0aecf61e.png)

Ej: Se quieren descargar los datos de este lugar
![imagen](https://user-images.githubusercontent.com/128641014/234921832-00a28794-45bf-43eb-971c-831a44a8c250.png)

Que se vea de esta forma la planilla descargada: 
1) SPI1_rio_aconcagua_petorca_2017 
2) SPI1_codigo_2017

Yo creo que es más fácil de visualizar el nombre, pero en algunos casos es muy largo

**Comment by jbkunst** [comment]
En el reporte existe la descarga de más de una variable, y tiene el siguiente formato:

![image](https://user-images.githubusercontent.com/56481/236276448-cc82e5c4-315a-4169-9d30-93c7f32c8270.png)
