### ISSUE TITLE
Estado de la página con las mejoras

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#34]
@jbkunst @frzambra @joaquinRiquelme He estado revisando la página toda la mañana y me es grato informar que con las mejoras tanto del plan de shiny como con la simplificación del gpkg correspondiente a la zona austral, la aplicación de unidades no se me ha caído ninguna vez, ha funcionado súper bien.

**Comment by frzambra** [comment]
Súper!
