### ISSUE TITLE
N/A en variable de precipitación

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#36]
Existe registro de NA en la variable precipitación en la sgtes unidades administrativas:

Zona central -> provincia: Isla de pascua no presenta datos.
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/e955bac0-90e6-46b3-87fe-79e1354c60e7)

Zona central -> comunas: Isla de pascua y Juan Fernández no presentan datos.
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/3242d82e-c045-4afc-bfd3-9b442df50d7f)

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/1877af18-c533-4c69-a250-45821928ac9c)

Zona central -> distrito censal: Isla de juan fernández aparece blanco el polígono, lo mismo pa isla de pascua. En la región metropolitana existen distritos censales sin variable precipitación.

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/f18793a6-1bd6-411a-b364-4e462564650b)
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/08333329-2f0c-48ae-8a89-606bc59ed339)

Zona central, zona sur-> cuencas: Isla de juan fernandez aparece gris y blanco, isla de pascua, blanco. Lo mismo ocurre para subcuencas y subsubcuencas. En la zona sur existen territorios en blanco 

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/f97e4a12-8778-4cd5-89c2-2f32cce24650)
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/2d7ac0c7-2897-4f39-a9e8-a00ce8893421)

**Comment by frzambra** [comment]
@jbkunst se revisó el gpkg y loa tabla de datos, en ambos casos está la unidad con datos. No tengo claro a que se puede deber esto, es solo alrededor de Chiloé.
