### ISSUE TITLE
Valores de precipitación muy altos

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#38]
@frzambra @jbkunst en la figura se presenta el gráfico de reporte de precipitación, pero en el año 2000 existe un valor demasiado alto 10000mm en el mes de junio en la región del maule (Figura 1). Por otro lado en la región de O'Higgins valores de 7500mm en junio del 2000 y de 1987 (Figura 2). ¿Esto está bien? Esto me parece raro porque en la leyenda del mapa el valor más alto es de 2000mm (Figura 3). Seguí revisando otros años y hay valores de 5000mm y existen otros casos igual que están muy altos.

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/bb631012-bd76-497a-86a5-3ee95dec823d)
Figura 1

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/6188b2a1-b5b5-42ab-bf4c-2ba6a1d4c219)
Figura 2

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/566f5ba3-db62-451b-b9e8-7c1fd95ee7d4)
Figura 3

**Comment by fabian199827** [comment]
Chequear valor de la region del Bio-Bio, está muy alto en comparación con otros años y otras regiones que debiesen ser igual o más lluviosas en la misma fecha

Valor alto en junio 2019
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/143f39b1-3a7f-420a-b55f-104d901be418)

Valor en Junio 2018
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/5b0cf67c-4822-4368-8fc6-ce5e20bab9bd)

Valor junio 2017
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/2d2cfdfa-e48c-4118-b928-7dd2a9d2ab87)

**Comment by frzambra** [comment]
revisar con los nuevos datos
