### ISSUE TITLE
N/A en variable de temperatura

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#39]
Unidad Provincia:
No hay dataos para isla de pascua
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/d4baa3b3-26b4-49be-bfaa-187e8d582c54)

Unidad comuna:
No hay datos para isla de pascua
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/69764fa3-c809-4ef1-8a36-0103bbc93181)

Unidad distrito censal
No hay datos para los distritos censales de la RM, ocurre lo mismo para las otras variables
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/9d1e7233-cc87-4591-9020-d6da7f083574)

Cuencas
No hay datos para isla de pascua y otros territorios cercanos (Figura 1). Hay lugares en blanco en Chile continental (Figura 2)
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/fcf862aa-89e3-45a1-8180-800d8cf3d7ee)
Figura 1

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/d4e96252-dcda-4410-b7f9-ded5d796b531)
Figura 2

Sub cuencas:
No hay datos en sectores con islas
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/83c833c4-9c54-4538-9620-b4954fe803a9)

Subsubcuencas
No hay datos en sectores con islas (Figura 1). Hay sectores en blanco en Chile continental
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/98c7b88d-a373-476d-aa60-4ab655404aea)
Figura 1

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/9e4c40f2-938f-40db-9bdf-ed94b99d1424)
Figura 2

Esta situación ocurre para todas las variables de temperatura (Tmin y Tmax)

**Comment by frzambra** [comment]
@jbkunst lo mismo que en #39. Hice la union de forma local utilizando los datos de la BBDD y los shapes simplificados que están en el repo, y no hay problema. Debe haber algun problema en el `join`

**Comment by jbkunst** [comment]
@frzambra 

Descubrí que el problema se produce cuando se utiliza un vector como `layerId` donde sus valores son duplicados.

```r
leaflet::addPolygons(
  ...,
  layerId = ~id_unidad,
  ...
)
```

Por ejemplo en subsuncuencas 
![image](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/56481/5450f842-fb8f-4305-8fd1-c0a7c523e633)

Como podemos proceder? Remover del gpk los duplicados?

**Comment by jbkunst** [comment]
Una plosible solución sería quedarse con la que posea área más grande? 

Ejemplos:

![image](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/56481/18a312fd-0661-4561-aa2e-8c8f14911d00)

![image](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/56481/4dda6ce4-7d6d-47d6-b2c4-1952890f611d)

**Comment by fabian199827** [comment]
@jbkunst  quedarnos con el área mas grande

**Comment by jbkunst** [comment]
Revisar por favor @fabian199827

**Comment by frzambra** [comment]
relacionado a #42 #43
