### ISSUE TITLE
Pop up en mapa

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#40]
Actualmente el pop up aparece como en la figura 1 y tiene la siguiente información: Nombre de la unidad y el valor de la variable correspondiente a la última fecha que aparece en el slider.
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/94a06661-11ee-4958-bc17-cc2b3f6413b6)
Figura 1

Que quede de esta forma (Figura 2) con información de lugar, fecha del último dato capturado, valor de la variable al día correpondiente y finalmente agregar la opción de generar reporte al pop up
  
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/5026a08f-84c8-4fec-8c34-4aaca3fb9b21)
Figura 2

**Comment by frzambra** [comment]
@frzambra agregar código del popup

**Comment by frzambra** [comment]
@jbkunst  acá un ejemplo.

```r
library(sf)
library(leaflet)
library(shinyWidgets)

nc = st_read(system.file("shape/nc.shp", package="sf")) |> 
  st_transform(4326)

popupName <- paste0('Código: 00192030','</br>',
                   'Cuenca: Maipo','</br>',
                   actionBttn('timeSeries','Serie Temporal',
                              size='xs', style = "simple", color = "primary",
                              icon = icon('line-chart'))
)
                   
                              
                              
leaflet() |> 
  addPolygons(data =nc,
              popup = popupName)

```

**Comment by fabian199827** [comment]
Poner pp en la leyenda y en popup con la fecha

**Comment by fabian199827** [comment]
Buena @jbkunst !, pero faltaría agregar la unidad de medida al pop up según corresponda la variable. con eso creo que estaríamos listos con el pop up

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/3915ec73-a2ee-4372-8228-14f8eec47690)

**Comment by fabian199827** [comment]
Listo!
