### ISSUE TITLE
Movimiento de slider "fecha"

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#41]
Cuando se mueve el slider para buscar fechas, los territorios en el mapa cambian con cada movimiento del slider, esto debería ser que cuando el slider se quede quieto, que en ese momento cambie el territorio remarcado en el mapa.

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/156cb0d5-e795-4544-b265-c7c1a6a301e5)

**Comment by frzambra** [comment]
@jbkunst  con `shiny::debounce` debería poder corregirse esto. Mira [aca](https://shiny.posit.co/r/reference/shiny/1.6.0/debounce.html)

**Comment by frzambra** [comment]
@jbkunst aumentar el tiempo y probar, por ejemplo 2000

**Comment by fabian199827** [comment]
@jbkunst @frzambra Ahora esto a mi parecer funciona bien, el mapa no da saltos entre fechas.

Sin embargo, mientras lo revisaba me di cuenta de que hay meses que no están, por ejemplo:

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/326fb803-b27c-42cd-ba57-7c839d09b6f2)

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/4bb65a47-2879-4f62-a06d-0fe1b85810d5)

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/3cec4eac-126c-4440-84fa-0429a273cb76)

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/c0b46153-7be6-49b8-ab65-874e821cad12)

Hay saltos entre fechas, derrepente se salta un mes, según yo estoy moviendo de a poco el slider y aun así se salta un mes.

**Comment by fabian199827** [comment]
Listo!
