### ISSUE TITLE
Variable temperatura con datos erróneos

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#42]
Existen valores en el mini gráfico que presentan valores erróneos, esto se repite para todas las unidades administrativas y solo para 1980 aprox.

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/2e4f6d90-648e-4631-90c7-7b99a70a3705)

**Comment by fabian199827** [comment]
@frzambra Revisar los datos de 1979

**Comment by frzambra** [comment]
relacionado con #43
