### ISSUE TITLE
Variables temperatura mínima y máxima

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#43]
Esta variable presenta el promedio mensual de las temperaturas mínimas de alguna unidad administrativa. Pero algunos valores registrados me generan ruido. Por ejemplo en la figura 1, está presentada la comuna de punta arenas con la variable temperatura mínima y los valores fluctúan entre los 27 y 27,5°C en junio, temperaturas que están muy cercanas a las de arica y en la misma fecha (Figura 2). Esto está bien?

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/a5da1d56-dbe2-4558-a484-81cb3ccb329f)
Figura 1

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/c08684eb-b4ae-4805-b085-7fb46acef521)
Figura 2

Por otro lado lo mismo para las temperaturas máximas. En meses fríos y en zonas australes, las temperaturas máximas fluctúan en los 27°C.

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/d8dbfc69-d140-455f-88b8-86e8137cf8cd)

**Comment by fabian199827** [comment]
Quizás las temperaturas están con error de transformación °K

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/37868afc-3fce-46f4-a673-9e2ffaa18983)

**Comment by frzambra** [comment]
@frzambra revisar script extracción de datos, verificar transformación precipitación y temperatura

**Comment by fabian199827** [comment]
Dejo este comentario para comparar cuando se arreglen las unidades de medida.

Esto es lo que aparece en ODES Temperaturas pormedio de 27°C aprox:
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/869a75ed-3920-4687-80ee-c321ea0463cd)

Y esto es lo que dice el climograma de Rancagua rescatado de (https://es.climate-data.org/america-del-sur/chile/vi-region-del-libertador-bernardo-o-higgins/rancagua-2053/#climate-graph)

Temperaturas de aproximadamente 5°C en julio
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/8c5acd95-cc6b-449d-871c-7378645f525a)

**Comment by fabian199827** [comment]
@jbkunst Encontré que la escala de las variables "Temperatura Mínima" y "Temperatura Máxima" no tienen el mismo formato con la variable "Temperatura":

Temperatura: Valores mayores rojos y mínimos azules
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/9c974def-f220-4d9e-bcdf-a84c4fdae7c4)

Temperatura Mínima: Valores mayores azules y mínimos rojos
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/6e393d9a-edf1-480a-8cd8-3d1fa4559e46)

Temperatura Máxima: Valores mayores azules y mínimos rojos
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/385c242b-1b41-4732-9528-1902cd50732c)

Dejémoslos con el formato de la variable "Temperatura".

**Comment by fabian199827** [comment]
Se debe verificar la temperatura de la RM en junio de 2019, creo que está muy frío en comparación con las regiones que se encuentran más al sur. No sé si se deberá al error antes reportado o por temas de unidades de escalado de valores, pero resalta mucho el color azul en este lugar.

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/c15f3773-7cfb-420e-b1ad-751ccd848c1a)

**Comment by fabian199827** [comment]
@frzambra Revisé los datos corregidos de temperatura, y ahora las escalas de medida están bien y los valores concuerdan con los climogramas:
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/4514c0a7-4718-4eb4-87bb-9a215e5a1ed3)

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/28a98900-8d6e-42d9-95c2-502fca29fae7)

**Comment by fabian199827** [comment]
@frzambra @jbkunst Me di cuenta que existen fechas intermedias con la variable temperatura mínima, que no registran datos

@frzambra Octubre 2013
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/0ac10590-f0ca-45a6-a42c-382d23316438)

Diciembre
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/3f8da4f2-f486-476b-9232-7365600c039c)

Está seleccionado el slider de fecha, hasta diciembre y en el minigráfico no se muestra esta fecha, debido a la falta de información.
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/a5c75f16-6892-4e4c-b954-2147a14f3b92)

En Febrero de 2014 vuelve a haber información
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/ea6b4f9b-4281-4eea-9d46-bd0a8c24a441)

**Comment by jbkunst** [comment]
![image](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/56481/b828cf98-9597-4ab9-92bd-89fae3d23499)

**Comment by frzambra** [comment]
@jbkunst @fabian199827 se reemplazaron todos los datos climáticos, por lo que hay que chequear nuevamente. Voy a cerrae este issue ya que corresponde a los datos antiguos.
