### ISSUE TITLE
Error en visualización de reporte

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#44]
No sé qué habrá pasado pero estaba revisando los datos del reporte y derrepente pincho en la opcion de generar reporte y se ve así:
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/cb79903b-d105-49e6-bc25-4eca672b9f1d)

Unos minutos antes no había habido problemas.

**Comment by jbkunst** [comment]
Creo @fabian199827  que esto es tema de datos, por favor, intenta ir agregando evidencia a issues que tienen relación -en este caso creo que #43 en lugar de ir creando nuevos issues por favor. Puede que la casuística/razón sea la misma.

Saludos,
