### ISSUE TITLE
Aplicación desconfigurada

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#45]
@frzambra @jbkunst Es raro, pero la aplicación funciona bien un momento y después se ve de esta forma:

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/82c48240-eda6-4f41-8697-16e0dd1e21ed)

Lo mismo ocurre en Estaciones, pero es intermitente.

**Comment by fabian199827** [comment]
**Desconexión del servidor:**

Macrozona: Todas
Unidad Administrativa: Provincias
Variable: Spei24
Fecha: 1979-01-01 --> 2017-09-01

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/0f1546ae-81d0-4ae4-a756-79f9ed6dee2c)

**Comment by jbkunst** [comment]
corregido
