### ISSUE TITLE
Macador de ubicación

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#46]
Que el macador cuándo se busque alguna ubicación en el mapa, aparezca como un pin de google maps y no con un cíirculo

Estado actual:
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/374784f1-4d97-432b-bf9c-7e71d55e2b03)

Como debería quedar:
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/bb96fcf8-7ee5-4379-b141-942a28f285b2)

Y también una vez que se encuentre el lugar y se borre del buscador, que también se borre el macador en el mapa (mantenerlo, sólo mientras la ubicación está en el buscador)

También que cuando se pinche en el localizador, se marque con un punto el jugar donde se localizó la posición 

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/bf5895a2-5ece-40f5-b5eb-094ab8f04def)

**Comment by jbkunst** [comment]
don @frzambra  tiene algun código que pueda reusar?
