### ISSUE TITLE
Unidad de medida "Demanda evapotranspirativa de la atmósfera"

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#47]
@frzambra Tengo una pregunta con respecto a la unidad de medida de esta variable. La demanda evapotranspirativa de la atmósfera está en Watts m-2? Por lo tanto esto me sugiere una unidad de potencia x unidad de superficie. Entonces estos valores quieren representar cuanta energía (proveniente de la radiación solar) se requiere para evapotranspirar cierto volumen de agua? O solo representa la cantidad de radiacion solar incidente sobre la atmósfera en cierto lugar? (Según FAO56 para evapotranspirarr 1mm de agua se requieren 2,45MJ). 

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/650afdf1-de7c-46d5-83fe-1f4a6ac319c1)

**Comment by frzambra** [comment]
@fabian199827 debería estar en [mm]. [W/m2] es unidad de radiacion solar.

**Comment by fabian199827** [comment]
@frzambra Ok entonces hace referencia a la evapotranspiración mensual de una región en particular? Debería quedar así?

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/b7e8dae8-4e08-4e11-b1e0-1f8dfd443cf8)

Y quizás también cambiar "demanda evapotranspirativa de la atmósfera" por "Evapotranspiración" y que finamente quede así:

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/847a097b-29cb-49d3-84d7-855d6a54e45b)

**Comment by fabian199827** [comment]
Dejarlo como ETo (mm/mes)
