### ISSUE TITLE
Desconexión de servidor

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#50]
@jbkunst @frzambra Reporto una caida de servidor que ocurre muy pocas veces, pero ocurre. 

Mientras reviso la página, se cae y aparece el mensaje de caida de servidor y con el plan de Shiny actualizado (https://frzambra.shinyapps.io/odes-unidades-shiny-app/), no he encontrado un patrón en los selectores del panel que causen esto, sólo ocurre de vez en cuando.

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/15a182a4-8dcc-460b-9526-f5e53939cc12)

Vuelve a la normalidad después de aprox 10 minutos.

Descubrí que se cae mayormente cuando se manipula mucho el slider defechas para buscar un mes en específico
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/7c93c410-3a52-406d-ae5a-b471aa00dafe)

**Comment by jbkunst** [comment]
Deberemos probar con @frzambra para que al momento de ver la desconexión revisemos los logs
