### ISSUE TITLE
leer variables cuando se actualiza la BBDD

### ISSUE THREAD

**Issue by frzambra** [ODES-Chile/odes-unidades-shiny-app#51]
@jbkunst agregué unas nuevas variables a la BBDD, son unos spei nuevos, que van spei1_era:spei36_era. 

Sería bueno que la aplicación de forma automática leyera las variables que hay en la tabla y las agregué en los input. Para no tener que hacerlo manual, cada vez que se actualice la BBDD. ¿que te parece?

**Comment by jbkunst** [comment]
El tema es que hay sí o sí modificar _manualmente_ el excel. De forma general son dos fuentes de información:
1. La tabla que contiene los datos
2. Por otra parte el excel que contiene la meta data de las variables.

Por enede: hay que decidir pro ejemplo:
1. En caso que se actualice la tabla y no existan los datosn el planilla que se hace?

Lo discutimos en la reu.

**Comment by jbkunst** [comment]
Lo otro, quizás definir _no usar_ carácteres especiales en los nombres de las columnas, como `-` o ` ` (espacio). Utilizar de preferencia undesrcore. Dado que la planilla contendrá la forma _humana_ de mostrar el nombre de la variable en la app.

**Comment by jbkunst** [comment]
Se decide que se lee desde el archivo de variables https://github.com/ODES-Chile/odes-unidades-shiny-app/blob/main/data/parametros_variables.xlsx es decir:

1. debe tener nombre de columna
2. descripción
3. unidad de medida en caso que corresponda
4. colores
