### ISSUE TITLE
Cambiar leyenda de mapa base

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#52]
Cambiar el texto de selector de mapa base para que se entienda mejor qué tipo de mapa se quiere cargar.
@frzambra Estará bien el nombre de "Administrativo" para el mapa que carga por defecto la plataforma?

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/214cf590-55e8-4586-842b-6942244b108a)

Tambien agregar un ícono de "capa" de la siguiente forma:
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/09ff90f9-7f28-4382-9700-a568f286d43f)

Y que cuando se le haga click se despliegue el menú para seleccionar el tipo de mapa.
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/214cf590-55e8-4586-842b-6942244b108a)

**Comment by jbkunst** [comment]
Tienes algún código @fabian199827  que haga esto?

**Comment by fabian199827** [comment]
@jbkunst un código como tal para implementar esta acción no 😞, aún desconozco algún código para implementar acciones en páginas web, busqué pero no entiendo, pero puedo buscar el ícono, no sé serviría esto.
