### ISSUE TITLE
Pop Up inicial

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#53]
@frzambra que te parece que el pop up que aparece cuando uno se posa sobre alguna unidad administrativa, diga sólo el nombre de la unidad y no con los números de la variable que se tenga seleccionada?

Estado actual:
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/8e836b9c-d9f8-4fc5-b79d-8d0f76ce5091)

Con modificación:
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/01c186ee-4137-407d-8acf-841d110f4ff6)

**Comment by fabian199827** [comment]
mismo formato tooltip con hover

**Comment by jbkunst** [comment]
Se ha dejado la misma info al hover y en el click, la diferencia que hacer click aparece el boton del reporte

@fabian199827
