### ISSUE TITLE
Círculo selector de lugar

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#54]
@jbkunst @frzambra No sé si es posible pero creo que es necesario que cuando se busque algun lugar con buscador de ubicación (figura 1), una vez que es encontrada la ubicación y marcada por el círculo, este se borre del buscador, ya que este no desaparece nunca más (figura 2). Para que desaparezca se tiene que cargar denuevo la aplicación.

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/72ef313c-1cf8-437b-adde-79216dc7dc86)
Figura 1

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/1f821947-054a-4b42-ad33-8d5bc0203506)
Figura 2

**Comment by jbkunst** [comment]
@frzambra  Tienes algún código que haga esto?

**Comment by jbkunst** [comment]
Se ha eliminado la funcionalidad!

@fabian199827
