### ISSUE TITLE
Fecha en leyenda y pou up

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#55]
El estado actual de la fecha en la leyenda
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/386e1be5-0b12-4fd5-afe6-26c30ab5bbf7)

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/a7b1ba2e-bbdd-4a42-9bc5-4f8fcfa16327)

Dejar así:
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/71d008ce-ec50-4457-a8e0-4384225da1d7)

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/0684dbf9-4d9d-4c3d-a24a-1226aa14c405)

**Comment by fabian199827** [comment]
división escala de color

**Comment by jbkunst** [comment]
La escala ya se ha cambiado a jenkins. Faltaría definir los colores de cada variable, que en su principio se uso rojo/amarillo/azul.

@fabian199827
