### ISSUE TITLE
Error conecciones base de datos

### ISSUE THREAD

**Issue by frzambra** [ODES-Chile/odes-unidades-shiny-app#58]
@jbkunst uno de los errores más comunes que me ha pasado es 

`FATAL:  remaining connection slots are reserved for non-replication superuser connections`

Este es un problema en la cantidad de conecciones que permite la BBDD postgres. Creo va ha ser necesario migrar la BBDD a un servicio en el que podamos controlar la cantidad de conecciones con el objetivo de dar estabilidad a la plataforma.

**Comment by jbkunst** [comment]
Relacionado con #50

**Comment by fabian199827** [comment]
Lo dejo como observación. En base a lo mencionado en el issue #59 en que no hay información en la unidad de provincia, hice la prueba e hice click en "reporte sequía" y la página se cae
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/c009dd23-e350-4e61-bc83-bc6b41beecda)
