### ISSUE TITLE
Observaciones con los datos actualizados

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#59]
@jbkunst @frzambra Aquí documentaré mis observaciones después de la actualización de los datos. 

**UNIDADES CON VALORES NA:**

**Distrito censal:**
Esto ocurre para todas las variables excepto zNDVI. Para zNDVI no hay datos NA
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/16312e82-aa51-4f44-b31c-3033daba850d)

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/df0bd01e-7ae6-4862-adfe-0b6d0437e229)

**Provincia:**
Esto ocurre para todas las FECHAS y VARIABLES no aparecen datos para ninguna PROVINCIA.
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/134c3ea1-fc53-41d2-be34-e17d9d3ff89f)

**Comunas:**
Esto ocurre para las comunas de  algunas islas y para todas las variables
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/61e0d2bf-ab85-4e8b-8b80-1bf47a663bbd)
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/eec5c390-8c3c-4df9-b5dd-43b53ead65ad)
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/51ab9b92-f58a-4dd9-acd7-7835c3df4d12)

**Cuencas:**
Esto ocurre para las cuencas de algunas islas pero no para Chile continental
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/1c7037ab-2ed1-4272-bd7c-a96152da57dc)

Creo que hay que eliminar sólo isla de pascua, porque en Juan Fernández no ocurre
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/b99509b1-47f3-4f26-a552-f4aaee900b16)

**Subcuencas:**
Esto ocurre para las subcuencas de algunas Islas y para una parte de Chile continental pero la zona austral que se encuentra fragmentada. Ocurre para todas las variables excepto para zNDVI.
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/ae438e00-0114-4a11-8a39-5d2ecf78ac30)
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/1f03cd43-af69-4080-a033-923481fc5183)
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/bbe7ca20-900b-419a-8ae2-7c38ff644cf0)
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/16660f54-9ebc-4f02-b6c4-cbeda70593f9)
Para zNDVI ocurre solo para algunas islas, en la zona austral no ocurre
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/4ddcad4f-4c83-4fc8-a52a-8246ca2438aa)

**Subsubcuencas:**
Esto ocurre para todas las variables, algunas islas y parte de Chile continental
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/296f75ee-4243-40ab-b281-d3b05da66ba2)
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/36b2f14f-ea2e-41ca-93eb-5754448f0226)

zNDVI existen valores NA pero sólo para algunas islas y no para Chile continental
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/c3b40cd1-6a4e-4110-a39d-07fc02410ecd)

zNDVI Comineza desde febrero del año 2000. Esto está bien?
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/36438e2c-c4b8-4696-96e1-a14dfad4b198)

**Comment by fabian199827** [comment]
TIPEO
Nuevos indicadores
Este indicador quedará con este nombre?
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/b3a1f6a2-cdb5-4ecf-a529-83b4309cbe80)
O lo dejamos como SMA?

Creo que debemos estandarizar las unidades de medida:
Deja sólo como 1m o 100cm
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/74ff3ccc-00ab-47e8-b041-b8f0cb7499e9)
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/03621051-74c0-4c77-b25f-69d82fff5447)

Dejar como zNDVI
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/7f83e98f-0f71-41f0-b669-487ea2ca3279)

**Comment by fabian199827** [comment]
Creo que sería buena idea identificar a la fecha que corresponden las tarjetas generadas en el reporte

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/d5b7fc3c-31f0-4813-a427-d51108eefa77)

**Comment by fabian199827** [comment]
Aparece NA en el pop up, esto ocurre para EDDI, anomalía de la humedad de suelo a 1m y para zNDVI,  para todas las fechas, siendo que si hay datos.
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/eb472ca7-8d4d-4828-b768-9a0e5f33d4c3)
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/3aef3026-6a0d-4759-9fc8-1e40fb6f9093)
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/2a1c2974-5374-4c5d-991d-1b1ba8dd5ddf)

**Comment by fabian199827** [comment]
Se me ocurre que para las tarjetas del reporte agregarle una opción para hacer click en ella y que te dirija a una explicación de lo que significa cada índice y qué indica cada color
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/4bb0196f-9a9b-409d-81d2-8910858a863e)

**Comment by fabian199827** [comment]
En abril y mayo del 2023 no hay datos para zNDVI
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/a4aeac32-81c0-4dfa-ae85-6659b8ec3ef7)
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/8062afa1-0a83-4a6e-a7f9-41c3607631f9)

**Comment by fabian199827** [comment]
@jbkunst @joaquinRiquelme Debemos chequear los datos de provincias y cuencas ya que en algunas cuencas, provincias, comunas los títulos de los mini gráficos creo que se mezclan con subcuencas o con provincias, dependiendo del caso.

Cuenca
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/ad9c807c-d17b-46c3-beb8-e9c75aa52614)

Provincia
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/42a2a51c-d79a-40a3-b7d3-2562594f8802)

Provincia
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/09103372-12c1-46a7-9cc8-e2e8ca2e73ee)

Aquí encontré un caso donde en el título del mini gráfico cuando está seleccionada la opción de comuna, se mezclan con el nombre de la subsubcuenca presente en ese lugar
Comunas
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/52c63fa2-1176-40b4-b566-375e8bc6ad4c)

Subsubcuenca
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/01087883-c059-410c-9570-ea9474cf4bda)

**Comment by jbkunst** [comment]
Lo del nombre enbtre popup y minigrafico tiene issue #62

**Comment by fabian199827** [comment]
Ahh okey creí que era otra cosa 👍
