### ISSUE TITLE
Tiempo de espera y caída de página.

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#6]
Mucho tiempo de carga cuando se cambia de opción en “Macrozonas” . Luego de esperar mucho tiempo aparece este error de carga del servidor (imagen). Esto ocurrió en reiteradas ocasiones con varias combinaciones de opciones. 

![image](https://user-images.githubusercontent.com/128641014/227968215-696ec65f-07b5-4a5d-958e-d72cc53b772e.png)

**Comment by jbkunst** [comment]
relacionado con #12 , por tanto cerrado
