### ISSUE TITLE
Últimos menores cambios para lanzamiento en Aconcagua

### ISSUE THREAD

**Issue by frzambra** [ODES-Chile/odes-unidades-shiny-app#63]
Hola @jbkunst , estámos bien con los cambios. Las paletas de color funcionan bien para todos los indicadores de sequía.

Algunos menores cambios que sería bueno los pudieramos tener para el lunes son los siguientes:

1. El indicador `zndvi` deberiamos dejarlo con el nombre corto "zcNDVI-6" en la leyenda y en el reporte.
2. El indicador `sma_100cm` deberiamos dejarlo con el nombre corto zcSM-12" en la leyenda y en el reporte.

**Comment by jbkunst** [comment]
Hola @frzambra  recién llegué a la casa, no se si pueda alcanzar. Me confirmas por favor lo siguiente?

Leyenda te refieres al nombre indicado en el leaflet arriba a la derecha?
Reporte te reiferes al nombre indicado en el valuebox?

**Comment by frzambra** [comment]
Así es. Sí no alcanzas, no problem.
