### ISSUE TITLE
Agregar opción para descargar datos del minigráfico

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#65]
Que se descarguen los datos de la variable y el intervalo de fecha seleccionada

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/1f8c00ce-3aab-435e-9588-8f7f85553bda)

**Comment by jbkunst** [comment]
Esto ya está implementado, por favor testear.

@fabian199827

**Comment by fabian199827** [comment]
Funcionando perfecto
