### ISSUE TITLE
idea mini gráfico (spi y spei)

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#70]
Sólo como idea... presentar el mini gráfico en la plataforma así como se presentó en san felipe
![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/d0965f33-a5b0-4bd6-a2dc-ce92cf9758f3)

**Comment by jbkunst** [comment]
Cual sería la lista de los indicadores que veremos de esta forma?

**Comment by fabian199827** [comment]
spi, spei, eddi, zcNDVI, zcSM

**Comment by jbkunst** [comment]
Implementado, por favor testear.

@fabian199827
