### ISSUE TITLE
Visualización de leyenda

### ISSUE THREAD

**Issue by joaquinRiquelme** [ODES-Chile/odes-unidades-shiny-app#72]
Hola @frzambra @jbkunst @fabian199827 Estoy viendo la versión actual de unidades y creo que no se visualizan bien los textos de la leyenda de la derecha

![image](https://github.com/ODES-Chile/odes-estaciones-shiny-app/assets/43077799/43c4fc5c-6534-42f6-8bfe-ad4c64880a72)

EL punto decimal se ve muy poco y algunos valores tienen 1, 2 y otros 3 decimales, da para confusión y dificulta un poco la lectura rápida.

Saludos

**Comment by jbkunst** [comment]
ok! veré si podré cambiar esa sección a una tipografía distinta, de preferencia una monoespaciada, para proponerla y ver que se decide.

**Comment by fabian199827** [comment]
No sé que opinan, pero creo que el color gris presentado en la escala se confunde con los valores no disponibles, quizá se debería cambiar ese color gris en particular, quizás por un celeste tenue ya que corresponde a una precipitación considerable de notar.

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/593fbd84-149b-43e1-8144-eb0fd592aeb1)

**Comment by jbkunst** [comment]
@joaquinRiquelme 

Propuesta de tipografía.

La fuente de texto Raleway, como bien nos hiciste notar, no está dirigida para consumir textos muy largos ni cifras. Puse la fuente source sans pro de momento que es monoespaceada.

![image](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/56481/400c514a-a7ca-4b29-bac0-00b356b93caf)

**Comment by fabian199827** [comment]
Creo que ahora si está bien, sólo faltaría deja sólo un decimal después de la coma, esto para todas las variables

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/eed8a2bf-2d6b-4662-8202-30987cb34690)

**Comment by joaquinRiquelme** [comment]
@jbkunst Creo que está muchor mejor la tipografía, pero concuerdo con @fabian199827 que sería bueno dejar un número fijo de decimales.
