### ISSUE TITLE
zcNDVI sin información

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#73]
@frzambra Quizás ya lo sabías pero ahora estaba revisando la plataforma y el indicador zcNDVI aparece como NA. Esto es para todos los periodos e intervalos de tiempo del indicador.

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/0a8af5f3-de81-4792-a500-6eac88fc8626)

**Comment by frzambra** [comment]
Sí, es el único que no se actualiza al mismo tiempo que lo otros. Algo que tengo que ver como afrontar

**Comment by fabian199827** [comment]
Esto está pasando solamente para distrito censal

**Comment by frzambra** [comment]
En el caso de los distritos censales no está diponible ninguna fecha. @frzambra revisar
