### ISSUE TITLE
versión, licencia, DOI

### ISSUE THREAD

**Issue by frzambra** [ODES-Chile/odes-unidades-shiny-app#74]
Hice una publicación de prueba de la versión actual de la app en `zenodo`, con esto obtuvimos un [DOI](https://doi.org) el que nos sirve para referencias científicas. La idea es hacer lo mismo con las otras aplicaciones, además de publicar los datos por separado.

**Comment by frzambra** [comment]
@jbkunst le puse licencia [GPLv3 ](https://es.wikipedia.org/wiki/GNU_General_Public_License) a ver qué opinas?

**Comment by jbkunst** [comment]
@frzambra  de acuerdo!
