### ISSUE TITLE
caida de página (distrito censal)

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#75]
Algo está pasando con la unidad de distrito censal que se está cayendo. Hoy no he podido visualizarla:

![imagen](https://github.com/ODES-Chile/odes-unidades-shiny-app/assets/128641014/1dcc8c7c-c605-4cb3-8e9a-e0a98b6d29be)

**Comment by jbkunst** [comment]
@fabian199827 ,

Creo que @frzambra  se estaban subiendo los datos, Probé distrito central ahora, repondió lento, pero se mostró.

**Comment by fabian199827** [comment]
Si, noto lo mismo, creo que está un poco mas lenta que antes. Responde bien pero está demorando un poco más

**Comment by jbkunst** [comment]
Creo creo, debo confirmarlo, que al colocar muchas unidades la parte de jenkins es la que se demora, pues al filtrar una macrozona avanza bien

**Comment by fabian199827** [comment]
siii y con las unidades más grandes igual anda bien.

**Comment by frzambra** [comment]
> Creo creo, debo confirmarlo, que al colocar muchas unidades la parte de jenkins es la que se demora, pues al filtrar una macrozona avanza bien

Hay otra alternativa a `jenks` que es más rapida, creo que es `fisher`.
