### ISSUE TITLE
implementar pop up para citar

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#76]
@jbkunst implementar esta opcion

**Comment by jbkunst** [comment]
Se ha implementado en https://github.com/ODES-Chile/odes-unidades-shiny-app/commit/1936068d4173a7eff5bdeb0fa0e8e2b00995831f

Quizás que NO aparezca siempe para no molestar tanto, usualmente uno agrega una componente aleatoria para que se muestre el 50% de las veces en las descargas.
