### ISSUE TITLE
Traslape de los polígonos "macrozonas"

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#8]
Al momento de seleccionar las macrozonas de norte grande y después norte chico se traslapan los polígonos de ambas macrozonas, esto se deben separar y no se pueden traslapar (Figura 1).

![image](https://user-images.githubusercontent.com/128641014/227972699-0fb04c59-bb00-4366-b81c-7dacf7ad37ae.png)
Figura 1. Traslape de norte grande con norte chico

**Posibles soluciones:**
1) Definir las macrozonas como lo dice el ministerio de ciencias. Aquí se eliminaría la división de norte grande con norte chico (Figura 2):

![image](https://user-images.githubusercontent.com/128641014/227973317-0460848d-d2a1-4f30-8c91-da29ec8d1342.png)
Figura 2. Mapa de macrozonas proporcionado por el ministerio de ciencias.

2)	Dividir el norte grande y norte chico de la siguiente forma  (Figura 3 ):
 
![image](https://user-images.githubusercontent.com/128641014/227973423-f625e4af-7544-45a7-8cf6-c9fe1f7e4980.png)
Figura 3. División aproximada del norte grande con el norte chico.

**Comment by jbkunst** [comment]
realcionado con #9
