### ISSUE TITLE
Faltan comunas del norte chico.

### ISSUE THREAD

**Issue by fabian199827** [ODES-Chile/odes-unidades-shiny-app#9]
Falta identificar algunas comunas pertenecientes al norte chico (Figura 1)

![image](https://user-images.githubusercontent.com/128641014/227977023-fd5d5555-a930-4b11-9b9a-883879bdb288.png)
Figura 1. Comunas sin identificar en el norte chico

Posible solución:
Yo tengo un archivo .shp con todas las comunas a nivel nacional, si gustas, te lo puedo enviar. Aquí te dejo la identificación aproximada de las comunas que faltan (las comunas faltantes aparentemente pertenecen a la cuenca del Acoancagua, la comuna en amarillo es la comuna de Valparaíso, la misma que aparece abajo en la figura 1).

![image](https://user-images.githubusercontent.com/128641014/227980974-b5117806-dc7e-4470-a3ed-ff3cfceb7431.png)
 Figura 2. Capa vectorial de todas la comunas de Chile.

**Comment by frzambra** [comment]
> Falta identificar algunas comunas pertenecientes al norte chico (Figura 1)
> 
> ![image](https://user-images.githubusercontent.com/128641014/227977023-fd5d5555-a930-4b11-9b9a-883879bdb288.png) Figura 1. Comunas sin identificar en el norte chico
> 
> Posible solución: Yo tengo un archivo .shp con todas las comunas a nivel nacional, si gustas, te lo puedo enviar. Aquí te dejo la identificación aproximada de las comunas que faltan (las comunas faltantes aparentemente pertenecen a la cuenca del Acoancagua, la comuna en amarillo es la comuna de Valparaíso, la misma que aparece abajo en la figura 1).
> 
> ![image](https://user-images.githubusercontent.com/128641014/227980974-b5117806-dc7e-4470-a3ed-ff3cfceb7431.png) Figura 2. Capa vectorial de todas la comunas de Chile.

**Comment by frzambra** [comment]
> > Falta identificar algunas comunas pertenecientes al norte chico (Figura 1)
> > ![image](https://user-images.githubusercontent.com/128641014/227977023-fd5d5555-a930-4b11-9b9a-883879bdb288.png) Figura 1. Comunas sin identificar en el norte chico
> > Posible solución: Yo tengo un archivo .shp con todas las comunas a nivel nacional, si gustas, te lo puedo enviar. Aquí te dejo la identificación aproximada de las comunas que faltan (las comunas faltantes aparentemente pertenecen a la cuenca del Acoancagua, la comuna en amarillo es la comuna de Valparaíso, la misma que aparece abajo en la figura 1).
> > ![image](https://user-images.githubusercontent.com/128641014/227980974-b5117806-dc7e-4470-a3ed-ff3cfceb7431.png) Figura 2. Capa vectorial de todas la comunas de Chile.

Los polígonos de macrozonas corresponden a los que yo te envié Joshua. El problema se tiene que dar al hacer la intersección (`st_intersection`). Una posible solución puede ser usar `st_within`

![macrozonas](https://user-images.githubusercontent.com/4713428/228104335-550ca781-c501-4d63-83bd-a1aa2b10a0ba.png)

**Comment by jbkunst** [comment]
@frzambra le dará una vuelta 

En otro caso realizar una correción manual a `data/01_dunits.rds` 

![image](https://user-images.githubusercontent.com/56481/229212132-906e4804-cac4-4f16-8621-0bb92c872b90.png)

**Comment by frzambra** [comment]
Agregué dos gpkg nuevos

[macrozona 1](https://github.com/ODES-Chile/odes-unidades-shiny-app/blob/main/data/macro_zona_buf.gpkg) sirve para para todas las unidades salvo para cuencas. Se debería usar `st_join` de la siguiente forma:

```r
st_join(objeto_sf,macrozona, join = st_within)
```

El archivo [macrozona 2](https://github.com/ODES-Chile/odes-unidades-shiny-app/blob/main/data/macro_zona_buf_cuen.gpkg) debe utilizarce solo con las unidades de cuencas (no con subcuencas ni tampoco con subsubcuencas). De las misma forma se usa el `st_join`

**Comment by jbkunst** [comment]
@frzambra 

Reprocesé con los nuevos gpkg utilizando el script https://github.com/ODES-Chile/odes-unidades-shiny-app/blob/main/R/01_create_dunits.R 

Siguen quedando unidades sin macrozona. Menos que antes:

![image](https://user-images.githubusercontent.com/56481/230393606-889f0fa2-920a-44bf-93ff-e387151034a0.png)

Notar que tuve que setear el crs por al hacer el join me decian que no eran iguales.

![image](https://user-images.githubusercontent.com/56481/230393236-115cd13c-3b6b-46b4-b248-3ed7777de893.png)
